//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Likewise.LMC.Plugins.FileBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.Plugins.FileBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BlueArrows {
            get {
                object obj = ResourceManager.GetObject("BlueArrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CD/DVD Drive.
        /// </summary>
        internal static string CDDVD {
            get {
                return ResourceManager.GetString("CDDVD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to close the session {0}.
        ///Error: {1} .
        /// </summary>
        internal static string Error_DeleteSessionError {
            get {
                return ResourceManager.GetString("Error_DeleteSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error_PrintersError {
            get {
                return ResourceManager.GetString("Error_PrintersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close file:{0}.
        /// </summary>
        internal static string Error_UnableToCloseFile {
            get {
                return ResourceManager.GetString("Error_UnableToCloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the file {0}.
        ///Error: {1} .
        /// </summary>
        internal static string Error_UnableToCloseFileSelected {
            get {
                return ResourceManager.GetString("Error_UnableToCloseFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete printer the printer:{0}.
        /// </summary>
        internal static string Error_UnableToDelete {
            get {
                return ResourceManager.GetString("Error_UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the list of shared printers: {0}.
        /// </summary>
        internal static string Error_UnableToGetPrinterList {
            get {
                return ResourceManager.GetString("Error_UnableToGetPrinterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the list of shared printers..
        /// </summary>
        internal static string Error_UnableToGetPrinterList2 {
            get {
                return ResourceManager.GetString("Error_UnableToGetPrinterList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Shares.
        /// </summary>
        internal static string FileShares {
            get {
                return ResourceManager.GetString("FileShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap likewise_splash_screen {
            get {
                object obj = ResourceManager.GetObject("likewise_splash_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        internal static string OpenFiles {
            get {
                return ResourceManager.GetString("OpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sessions.
        /// </summary>
        internal static string OpenSessions {
            get {
                return ResourceManager.GetString("OpenSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lets you manage File and Print shares..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shared printer:{0}?.
        /// </summary>
        internal static string Prompt_DeletePrinter {
            get {
                return ResourceManager.GetString("Prompt_DeletePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to stop sharing {0}?.
        /// </summary>
        internal static string Prompt_DeleteShare {
            get {
                return ResourceManager.GetString("Prompt_DeleteShare", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap shared_folders {
            get {
                object obj = ResourceManager.GetObject("shared_folders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon SharedFolder {
            get {
                object obj = ResourceManager.GetObject("SharedFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon SharedFolder2 {
            get {
                object obj = ResourceManager.GetObject("SharedFolder2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Printers.
        /// </summary>
        internal static string SharedPrinters {
            get {
                return ResourceManager.GetString("SharedPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        internal static string sOpenFiles {
            get {
                return ResourceManager.GetString("sOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        internal static string sPrinters {
            get {
                return ResourceManager.GetString("sPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string sSessions {
            get {
                return ResourceManager.GetString("sSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        internal static string sShares {
            get {
                return ResourceManager.GetString("sShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        internal static string sTitleTopLevelTab {
            get {
                return ResourceManager.GetString("sTitleTopLevelTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
