//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Likewise.LMC.Plugins.FileBrowser.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.Plugins.FileBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Icon Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Computer_48 {
            get {
                object obj = ResourceManager.GetObject("Computer_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Library {
            get {
                object obj = ResourceManager.GetObject("Library", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Share {
            get {
                object obj = ResourceManager.GetObject("Share", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CD/DVD Drive.
        /// </summary>
        internal static string String_CDDVD {
            get {
                return ResourceManager.GetString("String_CDDVD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string String_Computer {
            get {
                return ResourceManager.GetString("String_Computer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string String_Desktop {
            get {
                return ResourceManager.GetString("String_Desktop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string String_Devices {
            get {
                return ResourceManager.GetString("String_Devices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string String_Documents {
            get {
                return ResourceManager.GetString("String_Documents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Shares.
        /// </summary>
        internal static string String_FileShares {
            get {
                return ResourceManager.GetString("String_FileShares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string String_Home {
            get {
                return ResourceManager.GetString("String_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string String_Music {
            get {
                return ResourceManager.GetString("String_Music", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string String_Network {
            get {
                return ResourceManager.GetString("String_Network", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        internal static string String_OpenFiles {
            get {
                return ResourceManager.GetString("String_OpenFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Sessions.
        /// </summary>
        internal static string String_OpenSessions {
            get {
                return ResourceManager.GetString("String_OpenSessions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string String_Pictures {
            get {
                return ResourceManager.GetString("String_Pictures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lets you manage File and Print shares..
        /// </summary>
        internal static string String_PluginDescription {
            get {
                return ResourceManager.GetString("String_PluginDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        internal static string String_TitleTopLevelTab {
            get {
                return ResourceManager.GetString("String_TitleTopLevelTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string String_Videos {
            get {
                return ResourceManager.GetString("String_Videos", resourceCulture);
            }
        }
    }
}
