/* Editor Settings: expandtabs and use 4 spaces for indentation
 * ex: set softtabstop=4 tabstop=8 expandtab shiftwidth=4: *
 * -*- mode: c, c-basic-offset: 4 -*- */

/*
 * Copyright Likewise Software    2004-2008
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the license, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.  You should have received a copy
 * of the GNU Lesser General Public License along with this program.  If
 * not, see <http://www.gnu.org/licenses/>.
 *
 * LIKEWISE SOFTWARE MAKES THIS SOFTWARE AVAILABLE UNDER OTHER LICENSING
 * TERMS AS WELL.  IF YOU HAVE ENTERED INTO A SEPARATE LICENSE AGREEMENT
 * WITH LIKEWISE SOFTWARE, THEN YOU MAY ELECT TO USE THE SOFTWARE UNDER THE
 * TERMS OF THAT SOFTWARE LICENSE AGREEMENT INSTEAD OF THE TERMS OF THE GNU
 * LESSER GENERAL PUBLIC LICENSE, NOTWITHSTANDING THE ABOVE NOTICE.  IF YOU
 * HAVE QUESTIONS, OR WISH TO REQUEST A COPY OF THE ALTERNATE LICENSING
 * TERMS OFFERED BY LIKEWISE SOFTWARE, PLEASE CONTACT LIKEWISE SOFTWARE AT
 * license@likewisesoftware.com
 */

namespace Likewise.LMC.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Icon addserver {
            get {
                object obj = ResourceManager.GetObject("addserver", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to It greatly simplifies user account management by allowing administrators to manage users and computers for all systems in their mixed network through a single identity management system..
        /// </summary>
        internal static string ADUC_Desc {
            get {
                return ResourceManager.GetString("ADUC_Desc", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        internal static string Caption_AddServer {
            get {
                return ResourceManager.GetString("Caption_AddServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export Favorites.
        /// </summary>
        internal static string Caption_FavoritesExport {
            get {
                return ResourceManager.GetString("Caption_FavoritesExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import Favorites.
        /// </summary>
        internal static string Caption_FavoritesImport {
            get {
                return ResourceManager.GetString("Caption_FavoritesImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise License Key Error.
        /// </summary>
        internal static string Caption_LicenseError {
            get {
                return ResourceManager.GetString("Caption_LicenseError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to License Terms Exceeded.
        /// </summary>
        internal static string Caption_LicenseTermsExceeded {
            get {
                return ResourceManager.GetString("Caption_LicenseTermsExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Manages Likewise Enterprise Cells.
        /// </summary>
        internal static string CellManager_Desc {
            get {
                return ResourceManager.GetString("CellManager_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected as {0} @ {1}.
        /// </summary>
        internal static string Connected_as {
            get {
                return ResourceManager.GetString("Connected_as", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ** Evaluation Copy **.
        /// </summary>
        internal static string DefaultAvnetCompany {
            get {
                return ResourceManager.GetString("DefaultAvnetCompany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to D4879-02130-E6E19-2DC80-00100-010E9-8E1D704.
        /// </summary>
        internal static string DefaultAvnetKey {
            get {
                return ResourceManager.GetString("DefaultAvnetKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ** Evaluation Copy **.
        /// </summary>
        internal static string DefaultCompany {
            get {
                return ResourceManager.GetString("DefaultCompany", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DDB79-0E233-D601E-2DC80-00300-010E9-8E1D704.
        /// </summary>
        internal static string DefaultKey {
            get {
                return ResourceManager.GetString("DefaultKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The current selection has already been added to the favorites..
        /// </summary>
        internal static string Error_AlreadyDefined {
            get {
                return ResourceManager.GetString("Error_AlreadyDefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The license key you entered is not a valid license key.  Please reenter the license key.
        ///
        ///If you have lost or forgotten the license key or believe this message to be in error, please contact support@likewisesoftware.com..
        /// </summary>
        internal static string Error_BadKey {
            get {
                return ResourceManager.GetString("Error_BadKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The remote installer could not be found.\n\nPlease reinstall the product on this computer..
        /// </summary>
        internal static string Error_CannotFindInstaller {
            get {
                return ResourceManager.GetString("Error_CannotFindInstaller", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve the computer name [{0}] into an IP address.
        ///
        ///Please provide a valid computer name or IP address..
        /// </summary>
        internal static string Error_CannotResolve {
            get {
                return ResourceManager.GetString("Error_CannotResolve", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to show the release notes file: {0}.
        /// </summary>
        internal static string Error_CannotShowReadme {
            get {
                return ResourceManager.GetString("Error_CannotShowReadme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not verify software license.
        ///
        ///Likewise will now exit..
        /// </summary>
        internal static string Error_CannotVerify_License {
            get {
                return ResourceManager.GetString("Error_CannotVerify_License", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Favorite [{0}] was not found in the favorite list..
        /// </summary>
        internal static string Error_FavoriteNotFound {
            get {
                return ResourceManager.GetString("Error_FavoriteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The address {0} is invalid. Please enter a valid IP address..
        /// </summary>
        internal static string Error_InvalidAddress {
            get {
                return ResourceManager.GetString("Error_InvalidAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name or IP address for the computer you wish to manage..
        /// </summary>
        internal static string Error_InvalidComputerName {
            get {
                return ResourceManager.GetString("Error_InvalidComputerName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Computer name is invalid..
        /// </summary>
        internal static string Error_InvalidComputerName2 {
            get {
                return ResourceManager.GetString("Error_InvalidComputerName2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Computer type is invalid..
        /// </summary>
        internal static string Error_InvalidComputerType {
            get {
                return ResourceManager.GetString("Error_InvalidComputerType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An invalid domain name [{0}] was selected.
        ///
        ///Please select a valid domain..
        /// </summary>
        internal static string Error_InvalidDomainName {
            get {
                return ResourceManager.GetString("Error_InvalidDomainName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The existing favorite name is invalid..
        /// </summary>
        internal static string Error_InvalidExistingFavorite {
            get {
                return ResourceManager.GetString("Error_InvalidExistingFavorite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new favorite name in invalid..
        /// </summary>
        internal static string Error_InvalidFavorite {
            get {
                return ResourceManager.GetString("Error_InvalidFavorite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More computers have been added to the favorites list than are allowed with your current license.
        ///
        ///{0} computers are allowed, but {1} are currently listed.
        ///
        ///To remove this message, please purchase a license for extra servers, or remove computers from the list of favorites..
        /// </summary>
        internal static string Error_LicenseTermsExceeded {
            get {
                return ResourceManager.GetString("Error_LicenseTermsExceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have not added any computers to your favorites list..
        /// </summary>
        internal static string Error_NoFavorites {
            get {
                return ResourceManager.GetString("Error_NoFavorites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The company name you entered does not correspond to the license key.  Please reenter the company name that you used to purchase the license key.
        ///
        ///If you have lost or forgotten the company name or believe this message to be in error, please contact support@likewisesoftware.com..
        /// </summary>
        internal static string Error_WrongCompanyName {
            get {
                return ResourceManager.GetString("Error_WrongCompanyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Lets administrators and users view the event logs on a local or remote machine..
        /// </summary>
        internal static string EventViewer_Desc {
            get {
                return ResourceManager.GetString("EventViewer_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File and Print Services in Likewise Software enable professionals to create advanced and cost-effective information networks that help maintain data availability and security, ease deployment and management, and integrate well with existing infrastructure..
        /// </summary>
        internal static string FilePrint_Desc {
            get {
                return ResourceManager.GetString("FilePrint_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Enterprise allows you to extend Active Directory group policies and security settings to non-Windows systems including - Linux, UNIX, and Mac. Now administrators can specify Cron policies on hundreds of machines without having to maintain them individually.
        /// </summary>
        internal static string GPM_Desc {
            get {
                return ResourceManager.GetString("GPM_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Group Policy Object Editor will help users to Create, modify, and manage your Active Directory group policies from a Linux or Mac computer
        ///
        ///.
        /// </summary>
        internal static string GPOE_Desc {
            get {
                return ResourceManager.GetString("GPOE_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usage: lacconsole [--loglevel  (Silent,Panic,Error,Normal,Verbose,Debug)]
        ///		  [--plugin (aduc,cellmanager,eventviewer,gpmc,fileandprint,lsa,auth,kerberos,lug)]
        ///		  [--platform (linux,mac,windows)]
        ///	          [--help/--h/help].
        /// </summary>
        internal static string HelpMsg {
            get {
                return ResourceManager.GetString("HelpMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allows the user to manage the principal names and service keys stored in a local key table. Principal and key pairs listed in the keytab allow services running on a host to authenticate themselves to the Key Distribution Center (KDC).
        /// </summary>
        internal static string KTAB_Desc {
            get {
                return ResourceManager.GetString("KTAB_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ({0} days remaining).
        /// </summary>
        internal static string Label_DaysRemaining {
            get {
                return ResourceManager.GetString("Label_DaysRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Licensed to {0}.
        /// </summary>
        internal static string Label_Licensee {
            get {
                return ResourceManager.GetString("Label_Licensee", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap likewise {
            get {
                object obj = ResourceManager.GetObject("likewise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap likewise_splash_screen {
            get {
                object obj = ResourceManager.GetObject("likewise_splash_screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Likewise Management Console allows you to view the status of your Active Directory domains, to run diagnostics and repair tools, and to manage your Likewise Enterprise licenses..
        /// </summary>
        internal static string LikewiseIConsole_Desc {
            get {
                return ResourceManager.GetString("LikewiseIConsole_Desc", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap likewiselogoV3 {
            get {
                object obj = ResourceManager.GetObject("likewiselogoV3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap likewiselogoV31 {
            get {
                object obj = ResourceManager.GetObject("likewiselogoV31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use Local Users and Groups to create and manage users and groups that are stored locally on a computer. .
        /// </summary>
        internal static string LUGDesc_Desc {
            get {
                return ResourceManager.GetString("LUGDesc_Desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Likewise Identity Service, or LWIS, is a next-generation authentication engine for Linux, Unix, and Mac OS X. A highly reliable and industrial-strength application, LWIS gives non-Windows computers advanced capabilities..
        /// </summary>
        internal static string LWIS_Desc {
            get {
                return ResourceManager.GetString("LWIS_Desc", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap LWlogo {
            get {
                object obj = ResourceManager.GetObject("LWlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Bitmap rgb_lw_ent {
            get {
                object obj = ResourceManager.GetObject("rgb_lw_ent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap rgb_lw_ent1 {
            get {
                object obj = ResourceManager.GetObject("rgb_lw_ent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want save LMC Console settings to {0}.
        /// </summary>
        internal static string SaveSettingsMessage {
            get {
                return ResourceManager.GetString("SaveSettingsMessage", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap small_logoGIF {
            get {
                object obj = ResourceManager.GetObject("small_logoGIF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon small_logoICON {
            get {
                object obj = ResourceManager.GetObject("small_logoICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Bitmap small_logoPNG {
            get {
                object obj = ResourceManager.GetObject("small_logoPNG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Unrecognized command line option [{0}]
        ///Usage: lacconsole [--loglevel  (Silent,Panic,Error,Normal,Verbose,Debug)]
        ///		  [--plugin (aduc,cellmanager,eventviewer,gpmc,fileandprint,lsa,auth,kerberos,lug)]
        ///		  [--platform (linux,mac,winodws)]
        ///	          [--help/--h/help].
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No favorites found..
        /// </summary>
        internal static string Warning_NoFavoritesFound {
            get {
                return ResourceManager.GetString("Warning_NoFavoritesFound", resourceCulture);
            }
        }
    }
}
