PROGRAM=LWIDSPlugIn
TYPE=dsplug

INFO=Info.plist

SOURCES=\
	LWAuthAdapter.cpp \
	LWIAttrLookup.cpp \
	LWIAttrValDataQuery.cpp \
	LWIBitVector.cpp \
	LWICRC.cpp \
	LWIDirNodeQuery.cpp \
	LWIGroup.cpp \
	LWIQuery.cpp \
	LWIRecTypeLookup.cpp \
	LWIRecordListQuery.cpp \
	LWIRecordQuery.cpp \
	LWISAuthAdapter.cpp \
	LWIUser.cpp \
	PlugInShell.cpp \
	ServerModule.c \
	ServerModuleLib.c \
	Utilities.cpp

FRAMEWORKS=CoreFoundation DirectoryService

LOCAL_CFLAGS=-Wno-unknown-pragmas

include Makefile.inc
