/* Editor Settings: expandtabs and use 4 spaces for indentation
 * ex: set softtabstop=4 tabstop=8 expandtab shiftwidth=4: *
 * -*- mode: c, c-basic-offset: 4 -*- */

/*
 * Copyright Likewise Software    2004-2008
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the license, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.  You should have received a copy
 * of the GNU Lesser General Public License along with this program.  If
 * not, see <http://www.gnu.org/licenses/>.
 *
 * LIKEWISE SOFTWARE MAKES THIS SOFTWARE AVAILABLE UNDER OTHER LICENSING
 * TERMS AS WELL.  IF YOU HAVE ENTERED INTO A SEPARATE LICENSE AGREEMENT
 * WITH LIKEWISE SOFTWARE, THEN YOU MAY ELECT TO USE THE SOFTWARE UNDER THE
 * TERMS OF THAT SOFTWARE LICENSE AGREEMENT INSTEAD OF THE TERMS OF THE GNU
 * LESSER GENERAL PUBLIC LICENSE, NOTWITHSTANDING THE ABOVE NOTICE.  IF YOU
 * HAVE QUESTIONS, OR WISH TO REQUEST A COPY OF THE ALTERNATE LICENSING
 * TERMS OFFERED BY LIKEWISE SOFTWARE, PLEASE CONTACT LIKEWISE SOFTWARE AT
 * license@likewisesoftware.com
 */

namespace Likewise.LMC.Plugins.EventlogPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.Plugins.EventlogPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cl&amp;ose.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cr&amp;eate.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to DELETE a group. Once deleted, group members will no longer be able to authenticate or access resources controlled by the group. Are you sure you want to delete group {0}?.
        /// </summary>
        internal static string DeleteGroupMessage {
            get {
                return ResourceManager.GetString("DeleteGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to DELETE a user account. Once deleted, the user will no longer be able to authenticate or access resources. Are you sure you want to delete user {0}?.
        /// </summary>
        internal static string DeleteUserMessage {
            get {
                return ResourceManager.GetString("DeleteUserMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Group.
        /// </summary>
        internal static string DsPickerReturnInValidGroup {
            get {
                return ResourceManager.GetString("DsPickerReturnInValidGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string ERROR_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ERROR_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the members cannot be added because their account type is invalid. No new members were added..
        /// </summary>
        internal static string ERROR_INVALID_MEMBER {
            get {
                return ResourceManager.GetString("ERROR_INVALID_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string ERROR_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("ERROR_INVALID_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the members specified were already members of the local group. No new members were added..
        /// </summary>
        internal static string ERROR_MEMBER_IN_ALIAS {
            get {
                return ResourceManager.GetString("ERROR_MEMBER_IN_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the members specified were not members of the local group. No members were deleted..
        /// </summary>
        internal static string ERROR_MEMBER_NOT_IN_ALIAS {
            get {
                return ResourceManager.GetString("ERROR_MEMBER_NOT_IN_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified local group does not exist..
        /// </summary>
        internal static string ERROR_NO_SUCH_ALIAS {
            get {
                return ResourceManager.GetString("ERROR_NO_SUCH_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the members specified do not exist. Therefore, no new members were added..
        /// </summary>
        internal static string ERROR_NO_SUCH_MEMBER {
            get {
                return ResourceManager.GetString("ERROR_NO_SUCH_MEMBER", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon EventViewer_48 {
            get {
                object obj = ResourceManager.GetObject("EventViewer_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while performing the operation..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum log file size must be in multiples of 64..
        /// </summary>
        internal static string MaxLogSize64Multiples {
            get {
                return ResourceManager.GetString("MaxLogSize64Multiples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password parameter is invalid..
        /// </summary>
        internal static string NERR_BadPassword {
            get {
                return ResourceManager.GetString("NERR_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return buffer is too small..
        /// </summary>
        internal static string NERR_BufTooSmall {
            get {
                return ResourceManager.GetString("NERR_BufTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group already exists..
        /// </summary>
        internal static string NERR_GroupExists {
            get {
                return ResourceManager.GetString("NERR_GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local group specified by the groupname parameter does not exist..
        /// </summary>
        internal static string NERR_GroupNotFound {
            get {
                return ResourceManager.GetString("NERR_GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This computer name is invalid..
        /// </summary>
        internal static string NERR_InvalidComputer {
            get {
                return ResourceManager.GetString("NERR_InvalidComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on the last administrative account..
        /// </summary>
        internal static string NERR_LastAdmin {
            get {
                return ResourceManager.GetString("NERR_LastAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only allowed on the primary domain controller of the domain..
        /// </summary>
        internal static string NERR_NotPrimary {
            get {
                return ResourceManager.GetString("NERR_NotPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements..
        /// </summary>
        internal static string NERR_PasswordTooShort {
            get {
                return ResourceManager.GetString("NERR_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on this special group..
        /// </summary>
        internal static string NERR_SpeGroupOp {
            get {
                return ResourceManager.GetString("NERR_SpeGroupOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account already exists..
        /// </summary>
        internal static string NERR_UserExists {
            get {
                return ResourceManager.GetString("NERR_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name could not be found..
        /// </summary>
        internal static string NERR_UserNotFound {
            get {
                return ResourceManager.GetString("NERR_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Please provide new group name:.
        /// </summary>
        internal static string NewGroupNameText {
            get {
                return ResourceManager.GetString("NewGroupNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation need to exactly match..
        /// </summary>
        internal static string PasswordValidator_NoMatch {
            get {
                return ResourceManager.GetString("PasswordValidator_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you view and manage the Likewise event log..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename group - .
        /// </summary>
        internal static string RenameGroupError {
            get {
                return ResourceManager.GetString("RenameGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename user - .
        /// </summary>
        internal static string RenameUserError {
            get {
                return ResourceManager.GetString("RenameUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Viewer.
        /// </summary>
        internal static string sTitleEventsPage {
            get {
                return ResourceManager.GetString("sTitleEventsPage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
