usr/bin/domainjoin-cli
usr/bin/lwinet
usr/bin/lwimsg
usr/bin/lwiinfo

usr/lib/likewise-open/ConfigureLogin
usr/lib/likewise-open/ConfigureShellPrompt
usr/lib/likewise-open/gpcron
usr/lib/likewise-open/Centeris.pm

usr/sbin/likewise-winbindd

usr/lib/likewise-open/idmap/lwopen.so
usr/lib/likewise-open/nss_info/lwopen.so

lib/libnss_lwidentity.so*

lib/security/pam_lwidentity.so

usr/lib/likewise-open/libwbclient.so*
usr/lib/likewise-open/libcentutils.so*
usr/lib/likewise-open/libgpglib.so*

etc/samba/lwiauthd.conf
etc/security/pam_lwidentity.conf
usr/share/lintian/overrides/likewise-open
