opt/likewise-open/bin/domainjoin-cli
opt/likewise-open/bin/lwinet
opt/likewise-open/bin/lwimsg
opt/likewise-open/bin/lwiinfo

opt/likewise-open/bin/CenterisPam.pm
opt/likewise-open/bin/Centeris.pm
opt/likewise-open/bin/ConfigureKrb5.pl
opt/likewise-open/bin/ConfigurePamForADLogin.pl
opt/likewise-open/bin/ConfigureSshForGssapi.pl
opt/likewise-open/bin/ConfigureShellPrompt.pl
opt/likewise-open/bin/ConfigureLogin.sh
opt/likewise-open/bin/gpcron.sh
opt/likewise-open/bin/domainjoin-gui

opt/likewise-open/bin/DomainJoinLib.dll
opt/likewise-open/bin/DomainJoin.exe

opt/likewise-open/sbin/likewise-winbindd

opt/likewise-open/lib/idmap/lwopen.so

lib/libnss_lwidentity.so.2
lib/security/pam_lwidentity.so

opt/likewise-open/include/samba/wbclient.h
usr/lib/libwbclient.so.0.1
usr/lib/libwbclient.so.0
usr/lib/libwbclient.so

etc/samba/lwiauthd.conf
etc/security/pam_lwidentity.conf
etc/init.d/likewise-open
etc/defaults/likewise-open
