//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Likewise.LMC.Plugins.RegistryViewerPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.Plugins.RegistryViewerPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon agent_lgr {
            get {
                object obj = ResourceManager.GetObject("agent_lgr", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CLASSES_ROOT.
        /// </summary>
        internal static string HKEY_CLASSES_ROOT {
            get {
                return ResourceManager.GetString("HKEY_CLASSES_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_CONFIG.
        /// </summary>
        internal static string HKEY_CURRENT_CONFIG {
            get {
                return ResourceManager.GetString("HKEY_CURRENT_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER.
        /// </summary>
        internal static string HKEY_CURRENT_USER {
            get {
                return ResourceManager.GetString("HKEY_CURRENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LIKEWISE.
        /// </summary>
        internal static string HKEY_LIKEWISE {
            get {
                return ResourceManager.GetString("HKEY_LIKEWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LIKEWISE_IMPORT.
        /// </summary>
        internal static string HKEY_LIKEWISE_IMPORT {
            get {
                return ResourceManager.GetString("HKEY_LIKEWISE_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE.
        /// </summary>
        internal static string HKEY_LOCAL_MACHINE {
            get {
                return ResourceManager.GetString("HKEY_LOCAL_MACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_USERS.
        /// </summary>
        internal static string HKEY_USERS {
            get {
                return ResourceManager.GetString("HKEY_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Viewer.
        /// </summary>
        internal static string RegistryViewer {
            get {
                return ResourceManager.GetString("RegistryViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Editor is an advanced tool for viewing and changing settings in your system registry. It contains information and settings for hardware, operating system software, most non-operating system software, and per-user settings. .
        /// </summary>
        internal static string RegistryViewerDesc {
            get {
                return ResourceManager.GetString("RegistryViewerDesc", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Reports {
            get {
                object obj = ResourceManager.GetObject("Reports", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
