
#define SRVSVC_SECONDS_IN_MINUTE (60)
#define SRVSVC_SECONDS_IN_HOUR   (60 * SRVSVC_SECONDS_IN_MINUTE)
#define SRVSVC_SECONDS_IN_DAY    (24 * SRVSVC_SECONDS_IN_HOUR)

#define SRVSVC_BYTES_IN_KB 	(1024)
#define SRVSVC_BYTES_IN_MB   	(1024 * SRVSVC_BYTES_IN_KB)
#define SRVSVC_BYTES_IN_GB    	(1024 * SRVSVC_BYTES_IN_MB)

#define SRVSVC_RECS_IN_K 		(1000)
#define SRVSVC_RECS_IN_M   	(1000 * SRVSVC_RECS_IN_K)

