//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Likewise.LMC.ServerControl.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.ServerControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Icon Admin {
            get {
                object obj = ResourceManager.GetObject("Admin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon Admin_White {
            get {
                object obj = ResourceManager.GetObject("Admin_White", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon agent_lgr {
            get {
                object obj = ResourceManager.GetObject("agent_lgr", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Bitmap BlueArrows {
            get {
                object obj = ResourceManager.GetObject("BlueArrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelling operation....
        /// </summary>
        internal static string CancellingOperation {
            get {
                return ResourceManager.GetString("CancellingOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelling the report. Please wait ....
        /// </summary>
        internal static string CancellingReport {
            get {
                return ResourceManager.GetString("CancellingReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Console.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Management Console.
        /// </summary>
        internal static string Caption_Console {
            get {
                return ResourceManager.GetString("Caption_Console", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Caption_Tasks {
            get {
                return ResourceManager.GetString("Caption_Tasks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Management Console.
        /// </summary>
        internal static string Caption_Wait {
            get {
                return ResourceManager.GetString("Caption_Wait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exception error: {0}.
        /// </summary>
        internal static string CaughtException {
            get {
                return ResourceManager.GetString("CaughtException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove license: {0}?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import {0} licenses ({1})?.
        /// </summary>
        internal static string ConfirmImport {
            get {
                return ResourceManager.GetString("ConfirmImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Revoke license: {0}?.
        /// </summary>
        internal static string ConfirmRevoke {
            get {
                return ResourceManager.GetString("ConfirmRevoke", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected as: {0} \ {1}.
        /// </summary>
        internal static string Connected_As {
            get {
                return ResourceManager.GetString("Connected_As", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;LMC_ConsoleFile ConsoleVersion=&quot;5.5&quot; ProgramMode=&quot;Author&quot;&gt;
        ///  &lt;ConsoleFileID&gt;{FC562630-0D97-11DD-BD0B-0800200C9A66}&lt;/ConsoleFileID&gt;
        ///  &lt;FrameState ShowMaximized=&quot;false&quot; ShowStatusBar=&quot;true&quot; ShowNavigationBar=&quot;true&quot; ShowNavigationTree=&quot;true&quot; ReadOnly=&quot;false&quot;&gt;
        ///    &lt;Rectangle Top=&quot;100&quot; Bottom=&quot;867&quot; Left=&quot;100&quot; Right=&quot;1123&quot;/&gt;
        ///  &lt;/FrameState&gt;
        ///  &lt;State&gt;
        ///  &lt;/State&gt;
        ///  &lt;Views&gt;
        ///  &lt;/Views&gt;
        ///&lt;/LMC_ConsoleFile&gt;
        ///.
        /// </summary>
        internal static string ConsoleSettings {
            get {
                return ResourceManager.GetString("ConsoleSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The report could not be completed due to the following error.
        ///Unable to login to the domain controller..
        /// </summary>
        internal static string ControllerLogonFailure {
            get {
                return ResourceManager.GetString("ControllerLogonFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to |CSV files (*.csv)|*.csv.
        /// </summary>
        internal static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics &amp; Migration.
        /// </summary>
        internal static string DiagnosticsAndRepairTabTitle {
            get {
                return ResourceManager.GetString("DiagnosticsAndRepairTabTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to run your e-mail client..
        /// </summary>
        internal static string Error_CannotEMail {
            get {
                return ResourceManager.GetString("Error_CannotEMail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to show the registration web page..
        /// </summary>
        internal static string Error_CannotShowRegistrationPage {
            get {
                return ResourceManager.GetString("Error_CannotShowRegistrationPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to show the support web page..
        /// </summary>
        internal static string Error_CannotShowSupportPage {
            get {
                return ResourceManager.GetString("Error_CannotShowSupportPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to start the agent installer: {0}.
        /// </summary>
        internal static string Error_CannotStartInstaller {
            get {
                return ResourceManager.GetString("Error_CannotStartInstaller", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise encountered an error while establishing a connection to {0}.
        ///
        ///The credentials you have provided do not have sufficient privileges to manage this machine..
        /// </summary>
        internal static string Error_Credentials {
            get {
                return ResourceManager.GetString("Error_Credentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise encountered an error while establishing a network session with {0}.
        ///Unknown username or incorrect password..
        /// </summary>
        internal static string Error_Credentials2 {
            get {
                return ResourceManager.GetString("Error_Credentials2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise encountered an error while establishing a network session with {0}.
        ///
        ///Unknown username, incorrect password or insufficient privileges..
        /// </summary>
        internal static string Error_FailedToConnect {
            get {
                return ResourceManager.GetString("Error_FailedToConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error connecting to machine..
        /// </summary>
        internal static string Error_FailedToConnect2 {
            get {
                return ResourceManager.GetString("Error_FailedToConnect2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise encountered an error while establishing a network session with {0}.
        ///
        ///Error: {1}.
        /// </summary>
        internal static string Error_FailedToConnect3 {
            get {
                return ResourceManager.GetString("Error_FailedToConnect3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid computer name..
        /// </summary>
        internal static string Error_InvalidComputerName {
            get {
                return ResourceManager.GetString("Error_InvalidComputerName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise cannot connect to {0}..
        /// </summary>
        internal static string Error_InvalidComputerType {
            get {
                return ResourceManager.GetString("Error_InvalidComputerType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Likewise agent is installed on {0} but the Samba service is not running.
        ///
        ///Start this service on your Linux server by typing: &quot;/etc/init.d/smb start&quot; from a Linux command
        ///shell, while logged on as root. This error can also occur if the firewall on the Linux server does
        ///not allow communication with the necessary Samba ports (e.g. 445)..
        /// </summary>
        internal static string Error_NoSamba {
            get {
                return ResourceManager.GetString("Error_NoSamba", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Likewise Agent on {0} needs to be updated.  It has version {1} and requires version {2} or greater.
        ///
        ///Please use the Install Agent button on top menu to update the agent..
        /// </summary>
        internal static string Error_OldAgent {
            get {
                return ResourceManager.GetString("Error_OldAgent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Likewise Agent on {0} is a newer version.  It has version {1}, and the Likewise client is version {2}.
        ///
        ///Please upgrade your Likewise client before trying to manage this server..
        /// </summary>
        internal static string Error_OldClient {
            get {
                return ResourceManager.GetString("Error_OldClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise encountered an error while establishing a network session with {0}.
        ///Multiple connections to a server or shared resource by the same user, using more than one user name, are not
        ///allowed. Disconnect all previous connections to the server or shared resource and try again..
        /// </summary>
        internal static string Error_TooManySesssions {
            get {
                return ResourceManager.GetString("Error_TooManySesssions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to assign license: {0}.
        /// </summary>
        internal static string Error_UnableToAssignLicense {
            get {
                return ResourceManager.GetString("Error_UnableToAssignLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to delete license: {0}.
        /// </summary>
        internal static string Error_UnableToDeleteLicense {
            get {
                return ResourceManager.GetString("Error_UnableToDeleteLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to revoke license: {0}.
        /// </summary>
        internal static string Error_UnableToRevokeLicense {
            get {
                return ResourceManager.GetString("Error_UnableToRevokeLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient priviliges to perform this operation..
        /// </summary>
        internal static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Console.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This computer already has a license assigned to it: {0}.
        /// </summary>
        internal static string ErrorComputerAlreadyHasAssignedLicense {
            get {
                return ResourceManager.GetString("ErrorComputerAlreadyHasAssignedLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to run migration tool: {0}.
        /// </summary>
        internal static string ErrorRunningMigration {
            get {
                return ResourceManager.GetString("ErrorRunningMigration", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating Report.
        /// </summary>
        internal static string GeneratingReportCaption {
            get {
                return ResourceManager.GetString("GeneratingReportCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report: {0}.
        /// </summary>
        internal static string GeneratingReportMessage {
            get {
                return ResourceManager.GetString("GeneratingReportMessage", resourceCulture);
            }
        }

        internal static System.Drawing.Icon GenericServer {
            get {
                object obj = ResourceManager.GetObject("GenericServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The default home directory does not contain %U. This may result in multiple users sharing a single home directory..
        /// </summary>
        internal static string HomeDirectoryNotPerUser {
            get {
                return ResourceManager.GetString("HomeDirectoryNotPerUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to |HTML files (*.html)|*.html.
        /// </summary>
        internal static string HTMLFilter {
            get {
                return ResourceManager.GetString("HTMLFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Imported on {0}.
        /// </summary>
        internal static string ImportDate {
            get {
                return ResourceManager.GetString("ImportDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Console.
        /// </summary>
        internal static string InfoPrompt {
            get {
                return ResourceManager.GetString("InfoPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string InitialTabName {
            get {
                return ResourceManager.GetString("InitialTabName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid computer!.
        /// </summary>
        internal static string InvalidComputer {
            get {
                return ResourceManager.GetString("InvalidComputer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid default home directory prefix.
        /// </summary>
        internal static string InvalidHomeDirectory {
            get {
                return ResourceManager.GetString("InvalidHomeDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid license!.
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid License File.
        /// </summary>
        internal static string InvalidLicenseFile {
            get {
                return ResourceManager.GetString("InvalidLicenseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid login shell.
        /// </summary>
        internal static string InvalidLoginShell {
            get {
                return ResourceManager.GetString("InvalidLoginShell", resourceCulture);
            }
        }

        internal static System.Drawing.Icon keys {
            get {
                object obj = ResourceManager.GetObject("keys", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Roles.
        /// </summary>
        internal static string Label_AddRemoveRoles {
            get {
                return ResourceManager.GetString("Label_AddRemoveRoles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}....
        /// </summary>
        internal static string Label_ConnectingTo {
            get {
                return ResourceManager.GetString("Label_ConnectingTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Label_Manage {
            get {
                return ResourceManager.GetString("Label_Manage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Label_Security {
            get {
                return ResourceManager.GetString("Label_Security", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Label_System {
            get {
                return ResourceManager.GetString("Label_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string Label_Utilities {
            get {
                return ResourceManager.GetString("Label_Utilities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Version.
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.likewise.com/resources/documentation_library/manuals/lwe/likewise-enterprise-guide.html#id2926175.
        /// </summary>
        internal static string LAC_Help {
            get {
                return ResourceManager.GetString("LAC_Help", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Library {
            get {
                object obj = ResourceManager.GetObject("Library", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only {0} out of {1} licenses were added. Some licenses might have already been present..
        /// </summary>
        internal static string LicenseCountMismatch {
            get {
                return ResourceManager.GetString("LicenseCountMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to License Management.
        /// </summary>
        internal static string LicenseTabTitle {
            get {
                return ResourceManager.GetString("LicenseTabTitle", resourceCulture);
            }
        }

        internal static System.Drawing.Icon likewise {
            get {
                object obj = ResourceManager.GetObject("likewise", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.likewise.com/resources/documentation_library/manuals/lwe/likewise-enterprise-guide.html#id2829393.
        /// </summary>
        internal static string LMC_CellManager_Help {
            get {
                return ResourceManager.GetString("LMC_CellManager_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.likewise.com/resources/documentation_library/manuals/lwe/likewise-enterprise-guide.html#id2895771.
        /// </summary>
        internal static string LMC_GPMC_Help {
            get {
                return ResourceManager.GetString("LMC_GPMC_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.likewise.com/resources/documentation_library/manuals/lwe/likewise-enterprise-guide.html#id2895771.
        /// </summary>
        internal static string LMC_GPOE_Help {
            get {
                return ResourceManager.GetString("LMC_GPOE_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://www.likewise.com/resources/documentation_library/manuals/lwe/likewise-enterprise-guide.html#id2926175.
        /// </summary>
        internal static string LMC_Help {
            get {
                return ResourceManager.GetString("LMC_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string Localhost {
            get {
                return ResourceManager.GetString("Localhost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        internal static string LWEventLogTabTitle {
            get {
                return ResourceManager.GetString("LWEventLogTabTitle", resourceCulture);
            }
        }

        internal static System.Drawing.Icon ManageServer {
            get {
                object obj = ResourceManager.GetObject("ManageServer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon navtriangle {
            get {
                object obj = ResourceManager.GetObject("navtriangle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon navtriangle_hover {
            get {
                object obj = ResourceManager.GetObject("navtriangle_hover", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Non-Schema.
        /// </summary>
        internal static string NonSchemaMode {
            get {
                return ResourceManager.GetString("NonSchemaMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No {0} have been specified to show on the report..
        /// </summary>
        internal static string NoObjectsInFilter {
            get {
                return ResourceManager.GetString("NoObjectsInFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must select at least one domain to run a report..
        /// </summary>
        internal static string NoReportDomainsSelected {
            get {
                return ResourceManager.GetString("NoReportDomainsSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not consistent!.
        /// </summary>
        internal static string NotConsistent {
            get {
                return ResourceManager.GetString("NotConsistent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This domain contains data created with an older version of Likewise. Consult the documentation to learn how to upgrade this information to the form used by Likewise Enterprise 4.0..
        /// </summary>
        internal static string Note_OldDataPresent {
            get {
                return ResourceManager.GetString("Note_OldDataPresent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A computer can only be assigned licenses from the domain to which it is joined. The computer &quot;{0}&quot; is not joined to domain {1}..
        /// </summary>
        internal static string NotSameDomain {
            get {
                return ResourceManager.GetString("NotSameDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected orphaned objects were deleted successfully..
        /// </summary>
        internal static string OrphanForm_CleanCompletedNoErrors {
            get {
                return ResourceManager.GetString("OrphanForm_CleanCompletedNoErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not all orphaned objects were deleted due to errors..
        /// </summary>
        internal static string OrphanForm_CleanCompletedWithErrors {
            get {
                return ResourceManager.GetString("OrphanForm_CleanCompletedWithErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current operation?.
        /// </summary>
        internal static string OrphanForm_ConfirmCancel {
            get {
                return ResourceManager.GetString("OrphanForm_ConfirmCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} orphaned object(s)?.
        /// </summary>
        internal static string OrphanForm_ConfirmDelete {
            get {
                return ResourceManager.GetString("OrphanForm_ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning for orphaned objects completed successfully..
        /// </summary>
        internal static string OrphanForm_ScanCompleteNoErrors {
            get {
                return ResourceManager.GetString("OrphanForm_ScanCompleteNoErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning for orphaned objects completed with errors..
        /// </summary>
        internal static string OrphanForm_ScanCompleteWithErrors {
            get {
                return ResourceManager.GetString("OrphanForm_ScanCompleteWithErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The report could not be completed due to the following error.
        ///{0}.
        /// </summary>
        internal static string ReportFailed {
            get {
                return ResourceManager.GetString("ReportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The computer does not have enough memory to generate this report. Try reducing the scope of the report by adjusting the report parameters..
        /// </summary>
        internal static string ReportOutOfMemory {
            get {
                return ResourceManager.GetString("ReportOutOfMemory", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Reports {
            get {
                object obj = ResourceManager.GetObject("Reports", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsTabTitle {
            get {
                return ResourceManager.GetString("ReportsTabTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Report - {0}.
        /// </summary>
        internal static string ReportTitle_Header {
            get {
                return ResourceManager.GetString("ReportTitle_Header", resourceCulture);
            }
        }

        internal static System.Drawing.Icon RoleConfigure {
            get {
                object obj = ResourceManager.GetObject("RoleConfigure", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample Report - {0}.
        /// </summary>
        internal static string SampleReport {
            get {
                return ResourceManager.GetString("SampleReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;report&gt;
        ///    &lt;date&gt;Todays date&lt;/date&gt;
        ///    &lt;domains&gt;
        ///        &lt;domain&gt;
        ///            &lt;name&gt;SAMPLE.DOMAIN.COM&lt;/name&gt;
        ///            &lt;shortDomainName&gt;SAMPLE&lt;/shortDomainName&gt;
        ///            &lt;enabled&gt;1&lt;/enabled&gt;
        ///            &lt;cells&gt;
        ///                &lt;cell&gt;
        ///                    &lt;name&gt;Sample Cell&lt;/name&gt;
        ///                    &lt;groups&gt;
        ///                        &lt;group&gt;
        ///                            &lt;name&gt;Sample Group&lt;/name&gt;
        ///                            &lt;accountName&gt;SAMPLE\Sample Group&lt;/accountName&gt;
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleReportXML {
            get {
                return ResourceManager.GetString("SampleReportXML", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string SchemaMode {
            get {
                return ResourceManager.GetString("SchemaMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select one or more domains to scan.
        /// </summary>
        internal static string SelectDomains {
            get {
                return ResourceManager.GetString("SelectDomains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string ServerLicenseType {
            get {
                return ResourceManager.GetString("ServerLicenseType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The report could not be completed due to the following error.
        ///The domain controller cannot be contacted..
        /// </summary>
        internal static string ServerNotOperationalMessage {
            get {
                return ResourceManager.GetString("ServerNotOperationalMessage", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Share {
            get {
                object obj = ResourceManager.GetObject("Share", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}  (site license).
        /// </summary>
        internal static string SiteLicenseType {
            get {
                return ResourceManager.GetString("SiteLicenseType", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status of {0}.
        /// </summary>
        internal static string StatusPage_Caption {
            get {
                return ResourceManager.GetString("StatusPage_Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AD objects.
        /// </summary>
        internal static string StatusPage_StoreDataInObjects {
            get {
                return ResourceManager.GetString("StatusPage_StoreDataInObjects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shadow AD objects.
        /// </summary>
        internal static string StatusPage_StoreDataInPartition {
            get {
                return ResourceManager.GetString("StatusPage_StoreDataInPartition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusTabTitle {
            get {
                return ResourceManager.GetString("StatusTabTitle", resourceCulture);
            }
        }

        internal static System.Drawing.Bitmap toCOMP_02 {
            get {
                object obj = ResourceManager.GetObject("toCOMP_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise.
        /// </summary>
        internal static string TopTabTitle {
            get {
                return ResourceManager.GetString("TopTabTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to load license file:
        ///
        ///{0}.
        /// </summary>
        internal static string UnableToLoadLicenseFile {
            get {
                return ResourceManager.GetString("UnableToLoadLicenseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unified.
        /// </summary>
        internal static string UnifiedMode {
            get {
                return ResourceManager.GetString("UnifiedMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Likewise Console.
        /// </summary>
        internal static string WaitCaption {
            get {
                return ResourceManager.GetString("WaitCaption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Importing licenses....
        /// </summary>
        internal static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeTabTitle {
            get {
                return ResourceManager.GetString("WelcomeTabTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        internal static string WorkstationLicenseType {
            get {
                return ResourceManager.GetString("WorkstationLicenseType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Licenses are for a different domain ({0}).
        /// </summary>
        internal static string WrongDomain {
            get {
                return ResourceManager.GetString("WrongDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string XMLFilter {
            get {
                return ResourceManager.GetString("XMLFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
