#!/bin/sh

BASEDIR=`dirname $0`/../..
. ${BASEDIR}/packaging/scripts/functions
VERSION=$(get_lwopen_version)

/bin/rm -rf $BASEDIR/../likewise-open-$VERSION || exit 1
mkdir $BASEDIR/../likewise-open-$VERSION || exit 1
rsync -av --exclude=.git* $BASEDIR/ $BASEDIR/../likewise-open-$VERSION/ || exit 1

## Create orig.tar.gz neeed for ubuntu merges.
tar cvz  $BASEDIR/../likewise-open-$VERSION -f ../likewise-open_$VERSION.orig.tar.gz

cd $BASEDIR/../likewise-open-$VERSION
if [ ! -d debian ]; then
	cp -r packaging/debian debian
fi

# Let's build this thing
dpkg-buildpackage -rfakeroot

