#!/bin/sh

BASEDIR=`dirname $0`/../..
. ${BASEDIR}/packaging/scripts/functions
VERSION=$(get_lwopen_version)

/bin/rm -rf $BASEDIR/../likewise-open-$VERSION || exit 1
mkdir $BASEDIR/../likewise-open-$VERSION || exit 1
rsync -av --exclude=.git* $BASEDIR/ $BASEDIR/../likewise-open-$VERSION/ || exit 1
cd $BASEDIR/../likewise-open-$VERSION
if [ ! -d debian ]; then
	ln -s packaging/debian debian
fi

dpkg-buildpackage -rfakeroot

