/* Editor Settings: expandtabs and use 4 spaces for indentation
 * ex: set softtabstop=4 tabstop=8 expandtab shiftwidth=4: *
 * -*- mode: c, c-basic-offset: 4 -*- */

/*
 * Copyright Likewise Software    2004-2008
 * All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the license, or (at
 * your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
 * General Public License for more details.  You should have received a copy
 * of the GNU Lesser General Public License along with this program.  If
 * not, see <http://www.gnu.org/licenses/>.
 *
 * LIKEWISE SOFTWARE MAKES THIS SOFTWARE AVAILABLE UNDER OTHER LICENSING
 * TERMS AS WELL.  IF YOU HAVE ENTERED INTO A SEPARATE LICENSE AGREEMENT
 * WITH LIKEWISE SOFTWARE, THEN YOU MAY ELECT TO USE THE SOFTWARE UNDER THE
 * TERMS OF THAT SOFTWARE LICENSE AGREEMENT INSTEAD OF THE TERMS OF THE GNU
 * LESSER GENERAL PUBLIC LICENSE, NOTWITHSTANDING THE ABOVE NOTICE.  IF YOU
 * HAVE QUESTIONS, OR WISH TO REQUEST A COPY OF THE ALTERNATE LICENSING
 * TERMS OFFERED BY LIKEWISE SOFTWARE, PLEASE CONTACT LIKEWISE SOFTWARE AT
 * license@likewisesoftware.com
 */

namespace Likewise.LMC.Plugins.LUG.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Likewise.LMC.Plugins.LUG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Caption_General {
            get {
                return ResourceManager.GetString("Caption_General", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member Of.
        /// </summary>
        internal static string Caption_MemberOf {
            get {
                return ResourceManager.GetString("Caption_MemberOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cl&amp;ose.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Closed {
            get {
                object obj = ResourceManager.GetObject("Closed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cr&amp;eate.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Dashboard_48 {
            get {
                object obj = ResourceManager.GetObject("Dashboard_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are about to DELETE a group. Once deleted, group members will no longer be able to authenticate or access resources controlled by the group. Are you sure you want to delete group {0}?.
        /// </summary>
        internal static string DeleteGroupMessage {
            get {
                return ResourceManager.GetString("DeleteGroupMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are about to DELETE a user account. Once deleted, the user will no longer be able to authenticate or access resources. Are you sure you want to delete user {0}?.
        /// </summary>
        internal static string DeleteUserMessage {
            get {
                return ResourceManager.GetString("DeleteUserMessage", resourceCulture);
            }
        }

        internal static System.Drawing.Icon DisabledUser_16 {
            get {
                object obj = ResourceManager.GetObject("DisabledUser_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Group.
        /// </summary>
        internal static string DsPickerReturnInValidGroup {
            get {
                return ResourceManager.GetString("DsPickerReturnInValidGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string ERROR_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ERROR_ACCESS_DENIED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving group information:
        ///
        ///{0}.
        /// </summary>
        internal static string Error_CannotRetrieveGroupInfo {
            get {
                return ResourceManager.GetString("Error_CannotRetrieveGroupInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error retrieving user information:
        ///
        ///{0}.
        /// </summary>
        internal static string Error_CannotRetrieveUserInfo {
            get {
                return ResourceManager.GetString("Error_CannotRetrieveUserInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more of the members cannot be added because their account type is invalid. No new members were added..
        /// </summary>
        internal static string ERROR_INVALID_MEMBER {
            get {
                return ResourceManager.GetString("ERROR_INVALID_MEMBER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        internal static string ERROR_INVALID_PARAMETER {
            get {
                return ResourceManager.GetString("ERROR_INVALID_PARAMETER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more of the members specified were already members of the local group. No new members were added..
        /// </summary>
        internal static string ERROR_MEMBER_IN_ALIAS {
            get {
                return ResourceManager.GetString("ERROR_MEMBER_IN_ALIAS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more of the members specified were not members of the local group. No members were deleted..
        /// </summary>
        internal static string ERROR_MEMBER_NOT_IN_ALIAS {
            get {
                return ResourceManager.GetString("ERROR_MEMBER_NOT_IN_ALIAS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified local group does not exist..
        /// </summary>
        internal static string ERROR_NO_SUCH_ALIAS {
            get {
                return ResourceManager.GetString("ERROR_NO_SUCH_ALIAS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One or more of the members specified do not exist. Therefore, no new members were added..
        /// </summary>
        internal static string ERROR_NO_SUCH_MEMBER {
            get {
                return ResourceManager.GetString("ERROR_NO_SUCH_MEMBER", resourceCulture);
            }
        }

        internal static System.Drawing.Icon EventViewer_48 {
            get {
                object obj = ResourceManager.GetObject("EventViewer_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Groups.
        /// </summary>
        internal static string FilterAllGroups {
            get {
                return ResourceManager.GetString("FilterAllGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        internal static string FilterAllUsers {
            get {
                return ResourceManager.GetString("FilterAllUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Groups.
        /// </summary>
        internal static string FilterLocalGroups {
            get {
                return ResourceManager.GetString("FilterLocalGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Users.
        /// </summary>
        internal static string FilterLocalUsers {
            get {
                return ResourceManager.GetString("FilterLocalUsers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Groups.
        /// </summary>
        internal static string FilterSystemGroups {
            get {
                return ResourceManager.GetString("FilterSystemGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Users.
        /// </summary>
        internal static string FilterSystemUsers {
            get {
                return ResourceManager.GetString("FilterSystemUsers", resourceCulture);
            }
        }

        internal static System.Drawing.Icon Firewall {
            get {
                object obj = ResourceManager.GetObject("Firewall", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon FirewallOn {
            get {
                object obj = ResourceManager.GetObject("FirewallOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occured while performing the operation..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Label_General {
            get {
                return ResourceManager.GetString("Label_General", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Label_GroupsTab {
            get {
                return ResourceManager.GetString("Label_GroupsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member Of.
        /// </summary>
        internal static string Label_MemberOf {
            get {
                return ResourceManager.GetString("Label_MemberOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Label_StatusTab {
            get {
                return ResourceManager.GetString("Label_StatusTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unix Groups.
        /// </summary>
        internal static string Label_UnixGroupsTab {
            get {
                return ResourceManager.GetString("Label_UnixGroupsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unix Users.
        /// </summary>
        internal static string Label_UnixUsersTab {
            get {
                return ResourceManager.GetString("Label_UnixUsersTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Label_UsersTab {
            get {
                return ResourceManager.GetString("Label_UsersTab", resourceCulture);
            }
        }

        internal static System.Drawing.Icon likewise {
            get {
                object obj = ResourceManager.GetObject("likewise", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalGroup_16 {
            get {
                object obj = ResourceManager.GetObject("LocalGroup_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalGroup_24 {
            get {
                object obj = ResourceManager.GetObject("LocalGroup_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalGroup_32 {
            get {
                object obj = ResourceManager.GetObject("LocalGroup_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalGroup_48 {
            get {
                object obj = ResourceManager.GetObject("LocalGroup_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalGroups {
            get {
                object obj = ResourceManager.GetObject("LocalGroups", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalGroups_new {
            get {
                object obj = ResourceManager.GetObject("LocalGroups_new", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalUser {
            get {
                object obj = ResourceManager.GetObject("LocalUser", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalUser_16 {
            get {
                object obj = ResourceManager.GetObject("LocalUser_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalUser_24 {
            get {
                object obj = ResourceManager.GetObject("LocalUser_24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalUser_32 {
            get {
                object obj = ResourceManager.GetObject("LocalUser_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalUser_48 {
            get {
                object obj = ResourceManager.GetObject("LocalUser_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon LocalUser_new {
            get {
                object obj = ResourceManager.GetObject("LocalUser_new", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum log file size must be in multiples of 64..
        /// </summary>
        internal static string MaxLogSize64Multiples {
            get {
                return ResourceManager.GetString("MaxLogSize64Multiples", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password parameter is invalid..
        /// </summary>
        internal static string NERR_BadPassword {
            get {
                return ResourceManager.GetString("NERR_BadPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The return buffer is too small..
        /// </summary>
        internal static string NERR_BufTooSmall {
            get {
                return ResourceManager.GetString("NERR_BufTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The group already exists..
        /// </summary>
        internal static string NERR_GroupExists {
            get {
                return ResourceManager.GetString("NERR_GroupExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The local group specified by the groupname parameter does not exist..
        /// </summary>
        internal static string NERR_GroupNotFound {
            get {
                return ResourceManager.GetString("NERR_GroupNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This computer name is invalid..
        /// </summary>
        internal static string NERR_InvalidComputer {
            get {
                return ResourceManager.GetString("NERR_InvalidComputer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on the last administrative account..
        /// </summary>
        internal static string NERR_LastAdmin {
            get {
                return ResourceManager.GetString("NERR_LastAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This operation is only allowed on the primary domain controller of the domain..
        /// </summary>
        internal static string NERR_NotPrimary {
            get {
                return ResourceManager.GetString("NERR_NotPrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements..
        /// </summary>
        internal static string NERR_PasswordTooShort {
            get {
                return ResourceManager.GetString("NERR_PasswordTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on this special group..
        /// </summary>
        internal static string NERR_SpeGroupOp {
            get {
                return ResourceManager.GetString("NERR_SpeGroupOp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user account already exists..
        /// </summary>
        internal static string NERR_UserExists {
            get {
                return ResourceManager.GetString("NERR_UserExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user name could not be found..
        /// </summary>
        internal static string NERR_UserNotFound {
            get {
                return ResourceManager.GetString("NERR_UserNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Please provide new group name:.
        /// </summary>
        internal static string NewGroupNameText {
            get {
                return ResourceManager.GetString("NewGroupNameText", resourceCulture);
            }
        }

        internal static System.Drawing.Icon open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation need to exactly match..
        /// </summary>
        internal static string PasswordValidator_NoMatch {
            get {
                return ResourceManager.GetString("PasswordValidator_NoMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to rename group - .
        /// </summary>
        internal static string RenameGroupError {
            get {
                return ResourceManager.GetString("RenameGroupError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to rename user - .
        /// </summary>
        internal static string RenameUserError {
            get {
                return ResourceManager.GetString("RenameUserError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        internal static string sTitleEventsPage {
            get {
                return ResourceManager.GetString("sTitleEventsPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The group name is not valid..
        /// </summary>
        internal static string UERR_InvalidGroupName {
            get {
                return ResourceManager.GetString("UERR_InvalidGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The home directory is not valid..
        /// </summary>
        internal static string UERR_InvalidHomeDir {
            get {
                return ResourceManager.GetString("UERR_InvalidHomeDir", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user name is not valid..
        /// </summary>
        internal static string UERR_InvalidUserName {
            get {
                return ResourceManager.GetString("UERR_InvalidUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JAXRPCSERVLET28: Missing port information.
        /// </summary>
        internal static string UERR_JAXRPCERR {
            get {
                return ResourceManager.GetString("UERR_JAXRPCERR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File size is too large..
        /// </summary>
        internal static string UERR_JAXRPCMessage {
            get {
                return ResourceManager.GetString("UERR_JAXRPCMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot move the home directory as the destination directory already exists..
        /// </summary>
        internal static string UERR_UsersHomeDirAlreadyExists {
            get {
                return ResourceManager.GetString("UERR_UsersHomeDirAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot move the home directory to its own subdirectory..
        /// </summary>
        internal static string UERR_UsersHomeDirIsSubdirectoryException {
            get {
                return ResourceManager.GetString("UERR_UsersHomeDirIsSubdirectoryException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field contains invalid characters..
        /// </summary>
        internal static string UERR_UsersInvalidGecosException {
            get {
                return ResourceManager.GetString("UERR_UsersInvalidGecosException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified Group ID is not valid..
        /// </summary>
        internal static string UERR_UsersInvalidGroupidException {
            get {
                return ResourceManager.GetString("UERR_UsersInvalidGroupidException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid path containing an existing parent directory..
        /// </summary>
        internal static string UERR_UsersInvalidHomeDirException {
            get {
                return ResourceManager.GetString("UERR_UsersInvalidHomeDirException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified User ID is not valid..
        /// </summary>
        internal static string UERR_UsersInvalidUseridException {
            get {
                return ResourceManager.GetString("UERR_UsersInvalidUseridException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This Group ID is already used by another group..
        /// </summary>
        internal static string UERR_UsersNonUniqueGroupidException {
            get {
                return ResourceManager.GetString("UERR_UsersNonUniqueGroupidException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This User ID is already used by another user..
        /// </summary>
        internal static string UERR_UsersNonUniqueUseridException {
            get {
                return ResourceManager.GetString("UERR_UsersNonUniqueUseridException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user {0} already exists..
        /// </summary>
        internal static string UERR_UsersUserExistsException {
            get {
                return ResourceManager.GetString("UERR_UsersUserExistsException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The user account {0} is currently in use..
        /// </summary>
        internal static string UERR_UsersUserLoggedOnException {
            get {
                return ResourceManager.GetString("UERR_UsersUserLoggedOnException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Groups on {0}.
        /// </summary>
        internal static string UGPickerGroupTitle {
            get {
                return ResourceManager.GetString("UGPickerGroupTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Users on {0}.
        /// </summary>
        internal static string UGPickerUserTitle {
            get {
                return ResourceManager.GetString("UGPickerUserTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter group name..
        /// </summary>
        internal static string UGWARN_EnterName {
            get {
                return ResourceManager.GetString("UGWARN_EnterName", resourceCulture);
            }
        }

        internal static System.Drawing.Icon user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        internal static System.Drawing.Icon users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access denied, can not read: {0}.
        /// </summary>
        internal static string UWARN_AccessDenied {
            get {
                return ResourceManager.GetString("UWARN_AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid path and log file name.  Example: \var\log\messages.
        /// </summary>
        internal static string UWARN_FilePath {
            get {
                return ResourceManager.GetString("UWARN_FilePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new Group ID is not within the expected id range between {0} and {1}. Do you wish to proceed?.
        /// </summary>
        internal static string UWARN_GidOutOfRange {
            get {
                return ResourceManager.GetString("UWARN_GidOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new Group ID is not within the expected system id range between {0} and {1}. Do you wish to proceed?.
        /// </summary>
        internal static string UWARN_SysGidOutOfRange {
            get {
                return ResourceManager.GetString("UWARN_SysGidOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new User ID is not within the expected system id range between {0} and {1}. Do you wish to proceed?.
        /// </summary>
        internal static string UWARN_SysUidOutOfRange {
            get {
                return ResourceManager.GetString("UWARN_SysUidOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The new User ID is not within the expected id range between {0} and {1}. Do you wish to proceed?.
        /// </summary>
        internal static string UWARN_UidOutOfRange {
            get {
                return ResourceManager.GetString("UWARN_UidOutOfRange", resourceCulture);
            }
        }

        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
