#define LWMSG_SPEC_DEBUG

#include "includes.h"

LWMsgTypeSpec gFileHandleSpec[] =
{
    LWMSG_HANDLE(SMB_FILE_HANDLE),
    LWMSG_TYPE_END
};

LWMsgTypeSpec gSecurityTokenRepSpec[] =
{
    /* Begin structure */
    LWMSG_STRUCT_BEGIN(SMB_SECURITY_TOKEN_REP),
    /* Discriminator */
    LWMSG_MEMBER_UINT8(SMB_SECURITY_TOKEN_REP, type),
    /* Begin union */
    LWMSG_MEMBER_UNION_BEGIN(SMB_SECURITY_TOKEN_REP, payload),
    /* Union arm -- plain */
    LWMSG_MEMBER_STRUCT_BEGIN(union _SMB_SECURITY_TOKEN_U, plain),
    LWMSG_MEMBER_PWSTR(struct _SMB_SECURITY_TOKEN_PLAIN, pwszUsername),
    LWMSG_MEMBER_PWSTR(struct _SMB_SECURITY_TOKEN_PLAIN, pwszPassword),
    LWMSG_STRUCT_END,
    LWMSG_ATTR_TAG(SMB_SECURITY_TOKEN_TYPE_PLAIN),
    /* Union arm -- krb5 */
    LWMSG_MEMBER_STRUCT_BEGIN(union _SMB_SECURITY_TOKEN_U, krb5),
    LWMSG_MEMBER_PWSTR(struct _SMB_SECURITY_TOKEN_KRB5, pwszPrincipal),
    LWMSG_MEMBER_PWSTR(struct _SMB_SECURITY_TOKEN_KRB5, pwszCachePath),
    LWMSG_STRUCT_END,
    LWMSG_ATTR_TAG(SMB_SECURITY_TOKEN_TYPE_KRB5),
    /* End union */
    LWMSG_UNION_END,
    LWMSG_ATTR_DISCRIM(SMB_SECURITY_TOKEN_REP, type),
    /* End structure */
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gRequestConfigSpec[] =
{
    /* Begin structure */
    LWMSG_STRUCT_BEGIN(SMB_REQUEST),
    /* 32-bit unsigned integer */
    LWMSG_MEMBER_UINT32(SMB_REQUEST, dwCurTime),
    /* End structure */
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gStatusReplySpec[] =
{
    /* Begin structure */
    LWMSG_STRUCT_BEGIN(SMB_STATUS_REPLY),
    /* err - marshal as 32-bit unsigned integer */
    LWMSG_MEMBER_UINT32(SMB_STATUS_REPLY, dwError),
    /* End structure */
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gLogInfoSpec[] =
{
    /* Begin structure */
    LWMSG_STRUCT_BEGIN(SMB_LOG_INFO),
    /* 32-bit unsigned integer */
    LWMSG_MEMBER_UINT32(SMB_LOG_INFO, maxAllowedLogLevel),
    /* 32-bit unsigned integer */
    LWMSG_MEMBER_UINT32(SMB_LOG_INFO, logTarget),
    /* path - marshal as pointer to string */
    LWMSG_MEMBER_PSTR(SMB_LOG_INFO, pszPath),
    /* End structure */
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gCallNPRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_CALL_NP_REQUEST),
    LWMSG_MEMBER_PSECTOKEN(SMB_CALL_NP_REQUEST, pSecurityToken),
    LWMSG_MEMBER_PWSTR(SMB_CALL_NP_REQUEST, pwszNamedPipeName),
    LWMSG_MEMBER_UINT32(SMB_CALL_NP_REQUEST, dwInBufferSize),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_CALL_NP_REQUEST, pInBuffer),
    LWMSG_UINT8(char),
    LWMSG_POINTER_END,
    LWMSG_MEMBER_UINT32(SMB_CALL_NP_REQUEST, dwOutBufferSize),
    LWMSG_MEMBER_UINT32(SMB_CALL_NP_REQUEST, dwTimeout),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gCallNPResponseSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_CALL_NP_RESPONSE),
    LWMSG_MEMBER_UINT32(SMB_CALL_NP_RESPONSE, dwOutBufferSize),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_CALL_NP_RESPONSE, pOutBuffer),
    LWMSG_UINT8(char),
    LWMSG_POINTER_END,
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gSecurityAttributesSpec[] =
{
    LWMSG_STRUCT_BEGIN(SECURITY_ATTRIBUTES),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gCreateNPRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_CREATE_NP_REQUEST),
    LWMSG_MEMBER_PSECTOKEN(SMB_CREATE_NP_REQUEST, pSecurityToken),
    LWMSG_MEMBER_PWSTR(SMB_CREATE_NP_REQUEST, pwszName),
    LWMSG_MEMBER_UINT32(SMB_CREATE_NP_REQUEST, dwOpenMode),
    LWMSG_MEMBER_UINT32(SMB_CREATE_NP_REQUEST, dwPipeMode),
    LWMSG_MEMBER_UINT32(SMB_CREATE_NP_REQUEST, dwMaxInstances),
    LWMSG_MEMBER_UINT32(SMB_CREATE_NP_REQUEST, dwOutBufferSize),
    LWMSG_MEMBER_UINT32(SMB_CREATE_NP_REQUEST, dwInBufferSize),
    LWMSG_MEMBER_UINT32(SMB_CREATE_NP_REQUEST, dwDefaultTimeOut),
    LWMSG_MEMBER_POINTER(SMB_CREATE_NP_REQUEST, pSecurityAttributes, LWMSG_TYPESPEC(gSecurityAttributesSpec)),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gNamedPipeInfoSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_NP_INFO),
    LWMSG_MEMBER_UINT32(SMB_NP_INFO, dwFlags),
    LWMSG_MEMBER_UINT32(SMB_NP_INFO, dwOutBufferSize),
    LWMSG_MEMBER_UINT32(SMB_NP_INFO, dwInBufferSize),
    LWMSG_MEMBER_UINT32(SMB_NP_INFO, dwMaxInstances),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gTransactNPRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_TRANSACT_NP_REQUEST),
    LWMSG_MEMBER_TYPESPEC(SMB_TRANSACT_NP_REQUEST, hNamedPipe, gFileHandleSpec),
    LWMSG_MEMBER_UINT32(SMB_TRANSACT_NP_REQUEST, dwInBufferSize),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_TRANSACT_NP_REQUEST, pInBuffer),
    LWMSG_UINT8(char),
    LWMSG_POINTER_END,
    LWMSG_ATTR_LENGTH_MEMBER(SMB_TRANSACT_NP_REQUEST, dwInBufferSize),
    LWMSG_MEMBER_UINT32(SMB_TRANSACT_NP_REQUEST, dwOutBufferSize),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gWaitNPRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_WAIT_NP_REQUEST),
    LWMSG_MEMBER_PSECTOKEN(SMB_WAIT_NP_REQUEST, pSecurityToken),
    LWMSG_MEMBER_PWSTR(SMB_WAIT_NP_REQUEST, pwszName),
    LWMSG_MEMBER_UINT32(SMB_WAIT_NP_REQUEST, dwTimeout),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gClientComputerNameRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_GET_CLIENT_COMPUTER_NAME_REQUEST),
    LWMSG_MEMBER_TYPESPEC(SMB_GET_CLIENT_COMPUTER_NAME_REQUEST, hNamedPipe, gFileHandleSpec),
    LWMSG_MEMBER_UINT32(SMB_GET_CLIENT_COMPUTER_NAME_REQUEST, dwComputerNameMaxSize),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gClientComputerNameResponseSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_GET_CLIENT_COMPUTER_NAME_RESPONSE),
    LWMSG_MEMBER_PWSTR(SMB_GET_CLIENT_COMPUTER_NAME_RESPONSE, pwszName),
    LWMSG_MEMBER_UINT32(SMB_GET_CLIENT_COMPUTER_NAME_RESPONSE, dwLength),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gIdReplySpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_ID_REPLY),
    LWMSG_MEMBER_UINT32(SMB_ID_REPLY, dwId),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gPeekRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_PEEK_NP_REQUEST),
    LWMSG_MEMBER_TYPESPEC(SMB_PEEK_NP_REQUEST, hNamedPipe, gFileHandleSpec),
    LWMSG_MEMBER_UINT32(SMB_PEEK_NP_REQUEST, dwInBufferSize),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_PEEK_NP_REQUEST, pInBuffer),
    LWMSG_UINT8(char),
    LWMSG_POINTER_END,
    LWMSG_ATTR_LENGTH_MEMBER(SMB_PEEK_NP_REQUEST, dwInBufferSize),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gPeekResponseSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_PEEK_NP_RESPONSE),
    LWMSG_MEMBER_UINT32(SMB_PEEK_NP_RESPONSE, dwBytesRead),
    LWMSG_MEMBER_UINT32(SMB_PEEK_NP_RESPONSE, dwTotalBytesAvail),
    LWMSG_MEMBER_UINT32(SMB_PEEK_NP_RESPONSE, dwBytesLeftThisMessage),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gCreateFileRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_CREATE_FILE_REQUEST),
    LWMSG_MEMBER_PSECTOKEN(SMB_CREATE_FILE_REQUEST, pSecurityToken),
    LWMSG_MEMBER_PWSTR(SMB_CREATE_FILE_REQUEST, pwszFileName),
    LWMSG_MEMBER_UINT32(SMB_CREATE_FILE_REQUEST, dwDesiredAccess),
    LWMSG_MEMBER_UINT32(SMB_CREATE_FILE_REQUEST, dwSharedMode),
    LWMSG_MEMBER_UINT32(SMB_CREATE_FILE_REQUEST, dwCreationDisposition),
    LWMSG_MEMBER_UINT32(SMB_CREATE_FILE_REQUEST, dwFlagsAndAttributes),
    LWMSG_MEMBER_POINTER(SMB_CREATE_FILE_REQUEST, pSecurityAttributes, LWMSG_TYPESPEC(gSecurityAttributesSpec)),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gSetNamedPipeHandleSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_SETNAMEDPIPEHANDLESTATE_REQUEST),
    LWMSG_MEMBER_TYPESPEC(SMB_SETNAMEDPIPEHANDLESTATE_REQUEST, hPipe, gFileHandleSpec),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_SETNAMEDPIPEHANDLESTATE_REQUEST,    pdwMode),
    LWMSG_UINT8(uint32_t),
    LWMSG_POINTER_END,
    LWMSG_MEMBER_POINTER_BEGIN(SMB_SETNAMEDPIPEHANDLESTATE_REQUEST,    pdwCollectionCount),
    LWMSG_UINT8(uint32_t),
    LWMSG_POINTER_END,
    LWMSG_MEMBER_POINTER_BEGIN(SMB_SETNAMEDPIPEHANDLESTATE_REQUEST,    pdwTimeout),
    LWMSG_UINT8(uint32_t),
    LWMSG_POINTER_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gReadFileRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_READ_FILE_REQUEST),
    LWMSG_MEMBER_TYPESPEC(SMB_READ_FILE_REQUEST, hFile, gFileHandleSpec),
    LWMSG_MEMBER_UINT32(SMB_READ_FILE_REQUEST, dwBytesToRead),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gReadFileResponseSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_READ_FILE_RESPONSE),
    LWMSG_MEMBER_UINT32(SMB_READ_FILE_RESPONSE, dwBytesRead),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_READ_FILE_RESPONSE, pBuffer),
    LWMSG_UINT8(BYTE),
    LWMSG_POINTER_END,
    LWMSG_ATTR_LENGTH_MEMBER(SMB_READ_FILE_RESPONSE, dwBytesRead),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gWriteFileRequestSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_WRITE_FILE_REQUEST),
    LWMSG_MEMBER_TYPESPEC(SMB_WRITE_FILE_REQUEST, hFile, gFileHandleSpec),
    LWMSG_MEMBER_UINT32(SMB_WRITE_FILE_REQUEST, dwBytesToWrite),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_WRITE_FILE_REQUEST, pBuffer),
    LWMSG_UINT8(BYTE),
    LWMSG_POINTER_END,
    LWMSG_ATTR_LENGTH_MEMBER(SMB_WRITE_FILE_REQUEST, dwBytesToWrite),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gWriteFileResponseSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_WRITE_FILE_RESPONSE),
    LWMSG_MEMBER_UINT32(SMB_WRITE_FILE_RESPONSE, dwBytesWritten),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgTypeSpec gGetSessionKeyResponseSpec[] =
{
    LWMSG_STRUCT_BEGIN(SMB_GET_SESSION_KEY_RESPONSE),
    LWMSG_MEMBER_UINT32(SMB_GET_SESSION_KEY_RESPONSE, dwSessionKeyLength),
    LWMSG_MEMBER_POINTER_BEGIN(SMB_GET_SESSION_KEY_RESPONSE, pSessionKey),
    LWMSG_UINT8(BYTE),
    LWMSG_POINTER_END,
    LWMSG_ATTR_LENGTH_MEMBER(SMB_GET_SESSION_KEY_RESPONSE, dwSessionKeyLength),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

LWMsgProtocolSpec gLSMBProtocolSpec[] =
{
    LWMSG_MESSAGE(SMB_REFRESH_CONFIG,              gRequestConfigSpec),
    LWMSG_MESSAGE(SMB_REFRESH_CONFIG_SUCCESS,      gStatusReplySpec),
    LWMSG_MESSAGE(SMB_REFRESH_CONFIG_FAILED,       gStatusReplySpec),
    LWMSG_MESSAGE(SMB_SET_LOG_LEVEL,               gLogInfoSpec),
    LWMSG_MESSAGE(SMB_SET_LOG_LEVEL_SUCCESS,       gStatusReplySpec),
    LWMSG_MESSAGE(SMB_SET_LOG_LEVEL_FAILED,        gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_LOG_INFO,                gRequestConfigSpec),
    LWMSG_MESSAGE(SMB_GET_LOG_INFO_SUCCESS,        gLogInfoSpec),
    LWMSG_MESSAGE(SMB_GET_LOG_INFO_FAILED,         gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CALL_NAMED_PIPE,             gCallNPRequestSpec),
    LWMSG_MESSAGE(SMB_CALL_NAMED_PIPE_SUCCESS,     gCallNPResponseSpec),
    LWMSG_MESSAGE(SMB_CALL_NAMED_PIPE_FAILED,      gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CREATE_NAMED_PIPE,           gCreateNPRequestSpec),
    LWMSG_MESSAGE(SMB_CREATE_NAMED_PIPE_SUCCESS,   gFileHandleSpec),
    LWMSG_MESSAGE(SMB_CREATE_NAMED_PIPE_FAILED,    gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_NAMED_PIPE_INFO,         gFileHandleSpec),
    LWMSG_MESSAGE(SMB_GET_NAMED_PIPE_INFO_SUCCESS, gNamedPipeInfoSpec),
    LWMSG_MESSAGE(SMB_GET_NAMED_PIPE_INFO_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CONNECT_NAMED_PIPE,          gFileHandleSpec),
    LWMSG_MESSAGE(SMB_CONNECT_NAMED_PIPE_SUCCESS,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CONNECT_NAMED_PIPE_FAILED,   gStatusReplySpec),
    LWMSG_MESSAGE(SMB_TRANSACT_NAMED_PIPE,         gTransactNPRequestSpec),
    LWMSG_MESSAGE(SMB_TRANSACT_NAMED_PIPE_SUCCESS, gCallNPResponseSpec),
    LWMSG_MESSAGE(SMB_TRANSACT_NAMED_PIPE_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_WAIT_NAMED_PIPE,             gWaitNPRequestSpec),
    LWMSG_MESSAGE(SMB_WAIT_NAMED_PIPE_SUCCESS,     gStatusReplySpec),
    LWMSG_MESSAGE(SMB_WAIT_NAMED_PIPE_FAILED,      gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_COMPUTER_NAME,    gClientComputerNameRequestSpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_COMPUTER_NAME_SUCCESS, gClientComputerNameResponseSpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_COMPUTER_NAME_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_PROCESS_ID,         gFileHandleSpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_PROCESS_ID_SUCCESS, gIdReplySpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_PROCESS_ID_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_SERVER_PROCESS_ID,         gFileHandleSpec),
    LWMSG_MESSAGE(SMB_GET_SERVER_PROCESS_ID_SUCCESS, gIdReplySpec),
    LWMSG_MESSAGE(SMB_GET_SERVER_PROCESS_ID_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_SESSION_ID,         gFileHandleSpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_SESSION_ID_SUCCESS, gIdReplySpec),
    LWMSG_MESSAGE(SMB_GET_CLIENT_SESSION_ID_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_PEEK_NAMED_PIPE,               gPeekRequestSpec),
    LWMSG_MESSAGE(SMB_PEEK_NAMED_PIPE_SUCCESS,       gPeekResponseSpec),
    LWMSG_MESSAGE(SMB_PEEK_NAMED_PIPE_FAILED,        gStatusReplySpec),
    LWMSG_MESSAGE(SMB_DISCONNECT_NAMED_PIPE,         gFileHandleSpec),
    LWMSG_MESSAGE(SMB_DISCONNECT_NAMED_PIPE_SUCCESS, gStatusReplySpec),
    LWMSG_MESSAGE(SMB_DISCONNECT_NAMED_PIPE_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CREATE_FILE,                   gCreateFileRequestSpec),
    LWMSG_MESSAGE(SMB_CREATE_FILE_SUCCESS,           gFileHandleSpec),
    LWMSG_MESSAGE(SMB_CREATE_FILE_FAILED,            gStatusReplySpec),
    LWMSG_MESSAGE(SMB_SET_NAMED_PIPE_HANDLE_STATE,   gSetNamedPipeHandleSpec),
    LWMSG_MESSAGE(SMB_SET_NAMED_PIPE_HANDLE_STATE_SUCCESS, gStatusReplySpec),
    LWMSG_MESSAGE(SMB_SET_NAMED_PIPE_HANDLE_STATE_FAILED,  gStatusReplySpec),
    LWMSG_MESSAGE(SMB_READ_FILE,                     gReadFileRequestSpec),
    LWMSG_MESSAGE(SMB_READ_FILE_SUCCESS,             gReadFileResponseSpec),
    LWMSG_MESSAGE(SMB_READ_FILE_FAILED,              gStatusReplySpec),
    LWMSG_MESSAGE(SMB_WRITE_FILE,                    gWriteFileRequestSpec),
    LWMSG_MESSAGE(SMB_WRITE_FILE_SUCCESS,            gWriteFileResponseSpec),
    LWMSG_MESSAGE(SMB_WRITE_FILE_FAILED,             gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CLOSE_FILE,                    gFileHandleSpec),
    LWMSG_MESSAGE(SMB_CLOSE_FILE_SUCCESS,            gStatusReplySpec),
    LWMSG_MESSAGE(SMB_CLOSE_FILE_FAILED,             gStatusReplySpec),
    LWMSG_MESSAGE(SMB_GET_SESSION_KEY,               gFileHandleSpec),
    LWMSG_MESSAGE(SMB_GET_SESSION_KEY_SUCCESS,       gGetSessionKeyResponseSpec),
    LWMSG_MESSAGE(SMB_GET_SESSION_KEY_FAILED,        gStatusReplySpec),
    LWMSG_PROTOCOL_END
};

