#! /bin/sh
# ex: set tabstop=4 expandtab shiftwidth=4:
#
# Copyright (c) Likewise Corporation 2006
# Author: Gerald Carter <jerry@likewise.com>
#         Marc Guy <mguy@likewise.com>
#
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT# chkconfig: 35 92 9
#LWI_STARTUP_TYPE_REDHAT# description: Start and Stop the Likewise Registry Daemon 
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT#
#LWI_STARTUP_TYPE_SUSE### BEGIN INIT INFO
#LWI_STARTUP_TYPE_SUSE# Provides: lwregd
#LWI_STARTUP_TYPE_SUSE# Required-Start: $network $remote_fs
#LWI_STARTUP_TYPE_SUSE# Required-Stop: $network $remote_fs
#LWI_STARTUP_TYPE_SUSE# Default-Start: 3 5
#LWI_STARTUP_TYPE_SUSE# Default-Stop: 0 1 2 6
#LWI_STARTUP_TYPE_SUSE# Description: Start and Stop the Likewise Registry Daemon
#LWI_STARTUP_TYPE_SUSE### END INIT INFO

PROG_DESC="Likewise Registry Service"
PROG_BIN=PREFIX_DIR/sbin/lwregd
PROG_ARGS="--start-as-daemon"
PROG_ERR=/var/lib/likewise/lwregd/lwregd.err
PIDFILE=/var/run/lwregd.pid
SCRIPTNAME="lwregd"
STARTHOOK="fix_locale"

fix_locale()
{
    if [ "$LC_ALL" = "POSIX" ]
    then
        unset LC_ALL
        export LC_ALL
    fi
}

. PREFIX_DIR/bin/init-base.sh
