#!/bin/sh
# ex: set tabstop=4 expandtab shiftwidth=4:
#
# Copyright (c) 2006-2008 Likewise Software, Inc.
# Author: Gerald Carter <jerry@likewisesoftware.com>
#
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT# chkconfig: 35 91 9
#LWI_STARTUP_TYPE_REDHAT# description: Start and Stop the Likewise Likewise Named Pipe Client Daemon
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT#
#LWI_STARTUP_TYPE_SUSE### BEGIN INIT INFO
#LWI_STARTUP_TYPE_SUSE# Provides: npcmuxd
#LWI_STARTUP_TYPE_SUSE# Required-Start: $network
#LWI_STARTUP_TYPE_SUSE# Required-Stop: $network
#LWI_STARTUP_TYPE_SUSE# Default-Start: 3 5
#LWI_STARTUP_TYPE_SUSE# Default-Stop: 0 1 2 6
#LWI_STARTUP_TYPE_SUSE# Description: Start and Stop the Likewise Likewise Named Pipe Client Daemon
#LWI_STARTUP_TYPE_SUSE### END INIT INFO

PROG_DESC="Likewise Named Pipe Client Service"
PROG_BIN=PREFIX_DIR/sbin/npcmuxd
PROG_ARGS="--start-as-daemon"
PROG_ERR=/var/run/likewise-npcmuxd.err
SCRIPTNAME="npcmuxd"
PIDFILE=/var/run/npcmuxd.pid

. EXECDIR/init-base.sh
