#include "includes.h"

static LWMsgTypeSpec gLWNetDCInfoSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_DC_INFO),
    LWMSG_MEMBER_UINT32(LWNET_DC_INFO, dwPingTime),
    LWMSG_MEMBER_UINT32(LWNET_DC_INFO, dwDomainControllerAddressType),
    LWMSG_MEMBER_UINT32(LWNET_DC_INFO, dwFlags),
    LWMSG_MEMBER_UINT32(LWNET_DC_INFO, dwVersion),
    LWMSG_MEMBER_UINT16(LWNET_DC_INFO, wLMToken),
    LWMSG_MEMBER_UINT16(LWNET_DC_INFO, wNTToken),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszDomainControllerName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszDomainControllerAddress),
    LWMSG_MEMBER_ARRAY_BEGIN(LWNET_DC_INFO, pucDomainGUID),
    LWMSG_UINT8(UCHAR),
    LWMSG_ARRAY_END,
    LWMSG_ATTR_LENGTH_STATIC(LWNET_GUID_SIZE),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszNetBIOSDomainName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszFullyQualifiedDomainName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszDnsForestName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszDCSiteName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszClientSiteName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszNetBIOSHostName),
    LWMSG_MEMBER_PSTR(LWNET_DC_INFO, pszUserName),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCErrorSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_ERROR),
    LWMSG_MEMBER_UINT32(LWNET_IPC_ERROR, dwError),
    LWMSG_MEMBER_PSTR(LWNET_IPC_ERROR, pszErrorMessage),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCDCNameReqSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_DCNAME_REQ),
    LWMSG_MEMBER_PSTR(LWNET_IPC_DCNAME_REQ, pszServerFQDN),
    LWMSG_MEMBER_PSTR(LWNET_IPC_DCNAME_REQ, pszDomainFQDN),
    LWMSG_MEMBER_PSTR(LWNET_IPC_DCNAME_REQ, pszSiteName),
    LWMSG_MEMBER_UINT32(LWNET_IPC_DCNAME_REQ, dwFlags),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCDCTimeReqSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_DCTIME_REQ),
    LWMSG_MEMBER_PSTR(LWNET_IPC_DCTIME_REQ, pszDomainFQDN),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCDCTimeResSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_DCTIME_RES),
    LWMSG_MEMBER_UINT32(LWNET_IPC_DCTIME_RES, dcTime),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCDCReqSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_DC_REQ),
    LWMSG_MEMBER_PSTR(LWNET_IPC_DC_REQ, pszDomainFQDN),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCDCResSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_DC_RES),
    LWMSG_MEMBER_PSTR(LWNET_IPC_DC_RES, pszDCFQDN),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};

static LWMsgTypeSpec gLWNetIPCCurrentResSpec[] =
{
    LWMSG_STRUCT_BEGIN(LWNET_IPC_CURRENT_RES),
    LWMSG_MEMBER_PSTR(LWNET_IPC_CURRENT_RES, pszDomainFQDN),
    LWMSG_STRUCT_END,
    LWMSG_TYPE_END
};


static LWMsgProtocolSpec gLWNetIPCSpec[] =
{
    LWMSG_MESSAGE(LWNET_Q_DCTIME, gLWNetIPCDCTimeReqSpec),
    LWMSG_MESSAGE(LWNET_R_DCTIME_SUCCESS, gLWNetIPCDCTimeResSpec),
    LWMSG_MESSAGE(LWNET_R_DCTIME_FAILURE, gLWNetIPCErrorSpec),
    LWMSG_MESSAGE(LWNET_Q_DCINFO, gLWNetIPCDCNameReqSpec),
    LWMSG_MESSAGE(LWNET_R_DCINFO_SUCCESS, gLWNetDCInfoSpec),
    LWMSG_MESSAGE(LWNET_R_DCINFO_FAILURE, gLWNetIPCErrorSpec),
    LWMSG_MESSAGE(LWNET_Q_DC, gLWNetIPCDCReqSpec),
    LWMSG_MESSAGE(LWNET_R_DC_SUCCESS, gLWNetIPCDCResSpec),
    LWMSG_MESSAGE(LWNET_R_DC_FAILURE, gLWNetIPCErrorSpec),
    LWMSG_MESSAGE(LWNET_Q_CURRENT_DOMAIN, NULL),
    LWMSG_MESSAGE(LWNET_R_CURRENT_DOMAIN_SUCCESS, gLWNetIPCCurrentResSpec),
    LWMSG_MESSAGE(LWNET_R_CURRENT_DOMAIN_FAILURE, gLWNetIPCErrorSpec),
    LWMSG_PROTOCOL_END
};

LWMsgProtocolSpec*
LWNetIPCGetProtocolSpec(
    void
    )
{
    return gLWNetIPCSpec;
}
