/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux kyle-vmserver 2.6.22-14-generic #1 SMP Sun Oct 14 21:45:15 GMT 2007 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Thu Feb 28 14:16:16 PST 2008"
#define BUILD_ENV_SRCDIR "/home/kstemen/svn/users/kstemen/libsmbclient/samba-3.0.28/source"
#define BUILD_ENV_BUILDDIR "/home/kstemen/svn/users/kstemen/libsmbclient/samba-3.0.28/source"
#define BUILD_ENV_USER "kstemen"
#define BUILD_ENV_HOST "kyle-vmserver"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
