# Placing srvsvcd.reg here and not in likewise-open-server on purpose
etc/likewise-open/srvsvcd.reg

usr/lib/likewise-open/init-base.sh
usr/bin/conf2reg

usr/lib/likewise-open/libdomainjoin.so*
usr/lib/likewise-open/ConfigureLogin
usr/lib/likewise-open/gpcron
usr/bin/domainjoin-cli
usr/share/likewise-open/VERSION

# likewise-open-libs files
etc/likewise-open/pstore.reg

usr/lib/likewise-open/libunistr.so*
usr/lib/likewise-open/libgpglib.so*
usr/lib/likewise-open/libcentutils.so*
usr/lib/likewise-open/liblwmsg*.so*
usr/lib/likewise-open/liblwbase_nothr.so*
usr/lib/likewise-open/liblwbase.so*
usr/lib/likewise-open/liblwpsapi.so*
usr/lib/likewise-open/liblwps-regdb.so
usr/lib/likewise-open/liblwps-sqldb.so
usr/lib/likewise-open/liblwps-tdb.so
usr/lib/likewise-open/libtdb.so*
usr/lib/likewise-open/liblwmapsecurity.so*
usr/lib/likewise-open/liblwadvapi.so*
usr/lib/likewise-open/liblwadvapi_nothr.so*

# likewise-open-rpc files
etc/init.d/dcerpcd

etc/likewise-open/dcerpcd.reg

usr/bin/dceidl
usr/bin/uuid
usr/bin/idl

usr/sbin/dcerpcd

usr/share/dcerpc/idl.cat

usr/lib/likewise-open/libdcerpc.so*
usr/lib/likewise-open/libschannel.so*
usr/lib/likewise-open/libnetapi.so*
usr/lib/likewise-open/liblwrpcrt.so*
usr/lib/likewise-open/libktkrb5.so*
usr/lib/likewise-open/libmpr.so*

# likewise-open-lwsm files
etc/init.d/lwsmd

usr/bin/lwsm

usr/lib/likewise-open/init-lwsm.sh
usr/lib/likewise-open/liblwsmcommon.so*
usr/lib/likewise-open/liblwsmloader.so*
usr/lib/likewise-open/liblwsm.so*
usr/lib/likewise-open/lwsm-loader/*.so

usr/sbin/lwsmd

# likewise-open-lsass files
etc/init.d/lsassd
etc/likewise-open/lsassd.reg
etc/likewise-open/gss/mech

lib/libnss_lsass.so*
lib/security/pam_lsass.so
usr/share/pam-configs/likewise-open

usr/bin/lw-lsa
usr/bin/lw-migrator
usr/bin/lw-del-user
usr/bin/lw-add-user
usr/bin/lw-set-machine-sid
usr/bin/lw-dump-machine-acct
usr/bin/lw-mod-group
usr/bin/lw-find-user-by-name
usr/bin/lw-find-group-by-id
usr/bin/lw-ad-cache
usr/bin/lw-del-group
usr/bin/lw-enum-users
usr/bin/lw-find-by-sid
usr/bin/lw-ypcat
usr/bin/lw-find-group-by-name
usr/bin/lw-get-log-info
usr/bin/lw-enum-groups
usr/bin/lw-ypmatch
usr/bin/lw-get-metrics
usr/bin/lw-add-group
usr/bin/lw-mod-user
usr/bin/lw-get-status
usr/bin/lw-set-log-level
usr/bin/lw-refresh-configuration
usr/bin/lw-find-user-by-id
usr/bin/lw-list-groups-for-user
usr/bin/lw-trace-info

usr/lib/likewise-open/libdsapi.so*
usr/lib/likewise-open/liblsaaccess.so*
usr/lib/likewise-open/liblsaclient_ntlm.so*
usr/lib/likewise-open/liblsaclient.so*
usr/lib/likewise-open/liblsacommon.so*
usr/lib/likewise-open/liblsajoin.so*
usr/lib/likewise-open/liblsaserverapi.so*
usr/lib/likewise-open/liblsass_auth_provider_ad.so*
usr/lib/likewise-open/liblsass_auth_provider_local.so*
usr/lib/likewise-open/liblsaunistr.so*
usr/lib/likewise-open/liblwmapsecurity_lsass.so*
usr/lib/likewise-open/libntlmserver.so*
usr/lib/likewise-open/libsamdb.so*
usr/lib/likewise-open/libwbclient.so*
usr/lib/likewise-open/lwicompat_v*.so*
usr/sbin/lsassd

usr/bin/lw-update-dns

usr/lib/likewise-open/liblwdns.so*

# likewise-open-lwio files
etc/init.d/lwiod
etc/likewise-open/lwiod.reg

usr/bin/lwio-copy
usr/bin/lwio-driver
usr/bin/lwio-get-log-info
usr/bin/lwio-refresh
usr/bin/lwio-set-log-level

usr/lib/likewise-open/libiomgr2.so*
usr/lib/likewise-open/libiotest.sys.so*
usr/lib/likewise-open/liblwioclient.so*
usr/lib/likewise-open/liblwiocommon.so*
usr/lib/likewise-open/liblwioshareinfo.so*
usr/lib/likewise-open/liblwiosmbcommon.so*
usr/lib/likewise-open/librdr.sys.so*
usr/lib/likewise-open/libnpfs.sys.so*

usr/sbin/lwiod

# likewise-open-lwreg files
etc/init.d/lwregd
etc/likewise-open/lwreg.reg

usr/bin/lwregshell

usr/lib/likewise-open/libregclient.so*
usr/lib/likewise-open/libregipc.so*
usr/lib/likewise-open/libreglog_r.so*
usr/lib/likewise-open/libregparse.so*
usr/lib/likewise-open/libregserverapi.so*
usr/lib/likewise-open/libregserver_provider_sqlite.so*
usr/lib/likewise-open/libregutils.so*
usr/lib/likewise-open/librsutils.so*

usr/sbin/lwregd

# likewise-open-eventlog files
etc/init.d/eventlogd
etc/likewise-open/eventlogd.reg
usr/bin/lw-eventlog-cli
usr/lib/likewise-open/libeventlogutils.so*
usr/lib/likewise-open/libeventlog.so*
usr/lib/likewise-open/libeventlog-mac.so*
usr/sbin/eventlogd

# likewise-open-netlogon files
etc/init.d/netlogond
etc/likewise-open/netlogond.reg
etc/likewise-open/likewise-krb5-ad.conf
usr/bin/lw-get-current-domain
usr/bin/lw-export-dc-cache
usr/bin/lw-get-dc-list
usr/bin/lw-get-dc-name
usr/bin/lw-get-dc-time
usr/bin/lwnet-get-log-info
usr/bin/lwnet-set-log-level
usr/lib/likewise-open/liblwnetclientapi.so*
usr/lib/likewise-open/liblwnetcommon.so*
usr/sbin/netlogond

# apparmor HOMEDIRS tunable
etc/apparmor.d/tunables/home.d/likewise-open
