#! /bin/sh
# ex: set tabstop=4 expandtab shiftwidth=4:
#
# Copyright (c) Likewise Corporation 2006
# Author: Gerald Carter <jerry@likewise.com>
#
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT# chkconfig: 35 17 9
#LWI_STARTUP_TYPE_REDHAT# description: Start and Stop Likewise Service Manager
#LWI_STARTUP_TYPE_REDHAT###
#LWI_STARTUP_TYPE_REDHAT#
#LWI_STARTUP_TYPE_SUSE### BEGIN INIT INFO
#LWI_STARTUP_TYPE_SUSE# Provides: lwsmd
#LWI_STARTUP_TYPE_SUSE# Required-Start:
#LWI_STARTUP_TYPE_SUSE# Required-Stop:
#LWI_STARTUP_TYPE_SUSE# Default-Start: 3 5
#LWI_STARTUP_TYPE_SUSE# Default-Stop: 0 1 2 6
#LWI_STARTUP_TYPE_SUSE# Description: Start and Stop Likewise Service Manager
#LWI_STARTUP_TYPE_SUSE### END INIT INFO
#LWI_STARTUP_TYPE_ESX###
#LWI_STARTUP_TYPE_ESX# chkconfig: - 35 90
#LWI_STARTUP_TYPE_ESX# description: Start and Stop Likewise Service Manager
#LWI_STARTUP_TYPE_ESX###

PLATFORM=""
if [ "`uname -s`" = "VMkernel" ]; then
    PLATFORM="ESXI"
fi

PROG_DESC="Likewise Service Manager"
PROG_BIN=PREFIX_DIR/sbin/lwsmd
PROG_ARGS="--start-as-daemon --syslog"
PIDFILE=/var/run/lwsmd.pid
SCRIPTNAME="lwsmd"

if [ "$PLATFORM" = "ESXI" ]; then
   PROG_BIN=/sbin/lwsmd
   PROG_SCHED_PARAM="++group=likewise"
   # using watchdog, no need for --start-as-daemon
   PROG_ARGS="--syslog"
   PROG_ERR=/var/lib/likewise/lwsmd/lwsmd.err
   STARTHOOK="fix_locale"
fi

fix_locale()
{
    export LC_ALL="en_US.utf8"
    export LC_CTYPE="en_US.utf8"
}

if [ "$PLATFORM" = "ESXI" ]; then
   . /etc/likewise/init-base.sh
else
   . EXECDIR/init-base.sh
fi
