/* Generated by MakeKit */
/* Modified for dcerpc-win32 port using VS2008 */

#ifndef __MK_CONFIG_H__
#define __MK_CONFIG_H__

#define ATTRIBUTE_UNUSED
#define VERSION "1.1.0.7"
#define RPC_C_NP_DIR "\\\\PIPE\\.\\"
#define RPC_C_UXD_DIR "\\\\PIPE\\.\\"
#if defined(_MK_HOST) && !defined(ENABLE_PROT_NCACN)
#define ENABLE_PROT_NCACN 1
#endif
#if defined(_MK_HOST) && !defined(ENABLE_NAF_IP)
#define ENABLE_NAF_IP 1
#endif
#if defined(_MK_HOST) && !defined(ENABLE_AUTH_GSS_NEGOTIATE)
#define ENABLE_AUTH_GSS_NEGOTIATE 1
#endif
#if defined(_MK_HOST_X86_64) && !defined(SIZEOF_LONG)
#define SIZEOF_LONG 8
#endif
#if defined(_MK_HOST_X86_64) && !defined(SIZEOF_LONG_INT)
#define SIZEOF_LONG_INT 8
#endif
#if defined(_MK_HOST_X86_64) && !defined(SIZEOF_LONG_LONG_INT)
#define SIZEOF_LONG_LONG_INT 8
#endif
#if defined(_MK_HOST) && !defined(HAVE_FEATURES_H)
#define HAVE_FEATURES_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_SYS_CDEFS_H)
#define HAVE_SYS_CDEFS_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DLFCN_H)
#define HAVE_DLFCN_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_SYS_TIME_H)
#define HAVE_SYS_TIME_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_GETOPT_H)
#define HAVE_GETOPT_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_SYS_UN_H)
#define HAVE_SYS_UN_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_NL_TYPES_H)
#define HAVE_NL_TYPES_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_NET_IF_H)
#define HAVE_NET_IF_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_EXECINFO_H)
#define HAVE_EXECINFO_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_SYS_SELECT_H)
#define HAVE_SYS_SELECT_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_STRING_H)
#define HAVE_STRING_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_NET_IF_ARP_H)
#define HAVE_NET_IF_ARP_H 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_LIB_NSL)
#define HAVE_LIB_NSL 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_LIB_DL)
#define HAVE_LIB_DL 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_LIB_PTHREAD)
#define HAVE_LIB_PTHREAD 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_LIB_RT)
#define HAVE_LIB_RT 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_MEMCMP)
#define HAVE_MEMCMP 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_MEMCMP)
#define HAVE_DECL_MEMCMP 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_PTHREAD_YIELD)
#define HAVE_PTHREAD_YIELD 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_PTHREAD_YIELD)
#define HAVE_DECL_PTHREAD_YIELD 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_SCHED_YIELD)
#define HAVE_SCHED_YIELD 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_SCHED_YIELD)
#define HAVE_DECL_SCHED_YIELD 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_GETTIMEOFDAY)
#define HAVE_GETTIMEOFDAY 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_GETTIMEOFDAY)
#define HAVE_DECL_GETTIMEOFDAY 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_SOCKET)
#define HAVE_SOCKET 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_SOCKET)
#define HAVE_DECL_SOCKET 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_GETPEEREID)
#define HAVE_DECL_GETPEEREID 0
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_SETGRP)
#define HAVE_DECL_SETGRP 0
#endif
#if defined(_MK_HOST) && !defined(HAVE_SCANDIR)
#define HAVE_SCANDIR 1
#endif
#if defined(_MK_HOST) && !defined(HAVE_DECL_SCANDIR)
#define HAVE_DECL_SCANDIR 1
#endif
#if defined(_MK_HOST) && !defined(GETHOSTBYNAME_R_ARGS)
#define GETHOSTBYNAME_R_ARGS 6
#endif
#if defined(_MK_HOST) && !defined(BROKEN_ONCE_INIT)
#define BROKEN_ONCE_INIT 0
#endif
#if defined(_MK_BUILD) && !defined(HAVE_NL_TYPES_H)
#define HAVE_NL_TYPES_H 1
#endif

#endif
